### ISSUE TITLE
How to convert angular cli to web pack

### ISSUE THREAD

**Issue by SaravananArunagiri** [coreui/coreui-free-angular-admin-template#1]
I created asp.net core 2.0 project with angular 4. Now i want to add core UI layout to that project. but in my project i does not have any angular CLI. only have the web pack. how i convert this?

**Comment by Ryan6795** [comment]
@SaravananArunagiri  I've been running into a lot of issues with .net core 2.0 and angular 4. I don't think the way the modules are being lazy loaded is supported with angular 4. I maybe wrong. If anyone has any suggestions on how to get this working it would be great.

**Comment by dushkostanoeski** [comment]
I have no troubles with .net core 2.0 and angular 4. What's your webpack setup?

**Comment by Ryan6795** [comment]
I'm using a default template from visual studio, finding it a bit confusing as it doesn't seem to match any documentation out there in terms of structure.

This is my repo: https://github.com/Ryan6795/projectfinance/
where I wanted to plugin coreui.

**Comment by SaravananArunagiri** [comment]
@dushkostanoeski  Did you apply the CoreUI.io theme in your project

**Comment by dushkostanoeski** [comment]
Have a look at [this](https://github.com/damienbod/AngularWebpackVisualStudio)  setup, this is how I got mine to work.

**Comment by SaravananArunagiri** [comment]
@Ryan6795 @dushkostanoeski  Here i found the solution. It may be work.
CoreUI updated with npm.

 `npm install coreui.io@1.0.0-alpha.6`

Just now i saw in website [coreui.io](https://coreui.io)

**Comment by Ryan6795** [comment]
I found my issue I didnt include the angular2-router-loader in my webpack.config.js file. It now works in production but not in development. I receive "WinHttpException: The connection with the server was terminated abnormally". I think my issue is different that yours now.

**Comment by cvanslimming** [comment]
What worked best for me was starting out with angular cli project. Then started an empty asp.net core 2 project in the same directory. Then in the angular cli config file change the dist path to wwwroot. 

Check:
https://dustinewers.com/angular-cli-with-net-core/

**Comment by vardhineedik** [comment]
@SaravananArunagiri 
how to do it can you share the steps, please help me I am using asp core 2.0 with angular 4 webpack

**Comment by SaravananArunagiri** [comment]
@vardhineedik Take a look on https://www.codeproject.com/Articles/1206306/Integrating-ASP-Net-Core-and-Angular-project

**Comment by vardhineedik** [comment]
thanks @SaravananArunagiri 

i am able to create angular project but I want to integrate the CoreUI in my project (my project is angular 4 with webpack ) please help me how to integrate the coreUI .

thanks
