### ISSUE TITLE
Icons doesn't show

### ISSUE THREAD

**Issue by nwpuhmz** [coreui/coreui-free-angular-admin-template#10]
![1](https://user-images.githubusercontent.com/11306305/30774132-4ea26e98-a0b0-11e7-836e-51de69285150.PNG)
Could you give me some hints.Thx!

**Comment by jedsmithobd** [comment]
Is font-awesome loaded?

**Comment by mrholek** [comment]
Please check .angular-cli.json. You should have following code inside: 

"styles": [
  "../node_modules/font-awesome/css/font-awesome.css",
  "../node_modules/simple-line-icons/css/simple-line-icons.css",
  "scss/style.scss"
]
