### ISSUE TITLE
ERROR in ./src/scss/style.scss

### ISSUE THREAD

**Issue by mishrath** [coreui/coreui-free-angular-admin-template#105]
Unable to add new components and compile. 

  
ERROR in ./src/scss/style.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/scss/style.scss)
Module build failed:
undefined
^
      File to import not found or unreadable: node_modules/bootstrap/scss/functions.
When reporting a bug, include:

- Operating system and version (Windows7)
![image](https://user-images.githubusercontent.com/7740907/44498780-e96f0200-a6c3-11e8-967e-a8214dc70ef2.png)

**Comment by lepew911** [comment]
any resolution to this? i'm having same issue. thanks - stef

**Comment by UajoV6** [comment]
I've just deleted node_modules folder. did `npm i`. it compiled OK.

**Comment by ijunaid8989** [comment]
I am having the same issue and I am using yarn, but its not working, I am following VueJS https://github.com/coreui/coreui-free-vue-admin-template/blob/master/package.json#L16 theme.

**Comment by ijunaid8989** [comment]
> Unable to add new components and compile.
> 
> ERROR in ./src/scss/style.scss (./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--15-3!./src/scss/style.scss)
> Module build failed:
> undefined
> ^
> File to import not found or unreadable: node_modules/bootstrap/scss/functions.
> When reporting a bug, include:
> 
> * Operating system and version (Windows7)
>   ![image](https://user-images.githubusercontent.com/7740907/44498780-e96f0200-a6c3-11e8-967e-a8214dc70ef2.png)

Have you solved this in any way?
