### ISSUE TITLE
How to make a dynamic sidebar menu?

### ISSUE THREAD

**Issue by dolgovnv** [coreui/coreui-free-angular-admin-template#107]
I want to make a dynamic sidebar menu. For the test, I created a method changeMenu() in default-layout.component.ts.

I made the following changes (coreui-free-angular-admin-template-2.0.0-rc.4):

default-layout.component.html
`<a class="nav-link" href="#" (click)="changeMenu()">Dashboard</a>`

default-layout.component.ts
`public changeMenu() {
    this.navItems = [
      {
        name: 'Dashboard',
        url: '/dashboard',
        icon: 'icon-speedometer',
        badge: {
          variant: 'info',
          text: 'NEW'
        }
      }
    ];
  }`

I'm changing the array navItems. However, a strange bug occurs. A new item is added to the menu, and the old ones do not disappear.

Screenshot before clicking
![001](https://user-images.githubusercontent.com/9606505/44823606-8e498c00-ac3c-11e8-8aab-40d0edf33eba.png)

after clicking
![002](https://user-images.githubusercontent.com/9606505/44823607-8ee22280-ac3c-11e8-9f65-80a1d5e0fd4a.png)

**Comment by g0su** [comment]
same problem

**Comment by g0su** [comment]
just try to fix by create a custom sidebar-nav and replace app-sidebar-nav in default-layout
`import {Component, HostBinding, Input} from '@angular/core';

@Component({
    selector: 'app-sidebar-nav-custom',
    templateUrl: './sidebar-nav-custom.component.html',
    styleUrls: ['./sidebar-nav-custom.component.scss']
})


export class SidebarNavCustomComponent {
    @Input() navItems: Array<any>;
    @HostBinding('class.sidebar-nav') true;
    @HostBinding('attr.role') role;

    constructor() {
    }

    isDivider(navItem) {
        return !!navItem.divider
    }

    isTitle(navItem) {
        return !!navItem.title
    }

}
`
`<ul class="nav">
  <li *ngFor="let navitem of navItems" [ngClass]="{'nav-title': isTitle(navitem), 'nav-item': !(isTitle(navitem) || isDivider(navitem)), 'nav-divider': isDivider(navitem)}">
    <span *ngIf="isTitle(navitem)">{{navitem.name}}</span>
    <span *ngIf="isDivider(navitem)"></span>
    <a class="nav-link" *ngIf="!(isTitle(navitem) || isDivider(navitem))" href="/inventory/website">
      <i class="nav-icon" [ngClass]="navitem.icon"></i> {{navitem.name}}
    </a>
  </li>
</ul>`

**Comment by g0su** [comment]
just try to fix it by create a custom sidebar-nav and replace app-sidebar-nav in default-layout

```import {Component, HostBinding, Input} from '@angular/core';

@Component({
    selector: 'app-sidebar-nav-custom',
    templateUrl: './sidebar-nav-custom.component.html',
    styleUrls: ['./sidebar-nav-custom.component.scss']
})


export class SidebarNavCustomComponent {
    @Input() navItems: Array<any>;
    @HostBinding('class.sidebar-nav') true;
    @HostBinding('attr.role') role;

    constructor() {
    }

    isDivider(navItem) {
        return !!navItem.divider
    }

    isTitle(navItem) {
        return !!navItem.title
    }

}
```

```<ul class="nav">
  <li *ngFor="let navitem of navItems" [ngClass]="{'nav-title': isTitle(navitem), 'nav-item': !(isTitle(navitem) || isDivider(navitem)), 'nav-divider': isDivider(navitem)}">
    <span *ngIf="isTitle(navitem)">{{navitem.name}}</span>
    <span *ngIf="isDivider(navitem)"></span>
    <a class="nav-link" *ngIf="!(isTitle(navitem) || isDivider(navitem))" href="/inventory/website">
      <i class="nav-icon" [ngClass]="navitem.icon"></i> {{navitem.name}}
    </a>
  </li>
</ul>```

**Comment by dolgovnv** [comment]
Thank you. I did it in almost the same way.

**Comment by tsegato** [comment]
Just what I needed. However do you know how to call the custom component from another component? In my custom component I have following:

  loadNew(){
    alert('sadasdasdasd');
    console.log('dd');

    this.navItems = []; 

    this.navItems.push(
      {
        name: 'Dashboard 2',
        url: '/dashboard',
        icon: 'icon-speedometer',
       
      }
    );
  }

When I call that from another component the method is called, but it is not reflected in the UI. If I call the method from within the customer component it works.

import { Component, OnInit } from '@angular/core';
import { SidebarNavCustomComponentComponent} from '../sidebar-nav-custom-component/sidebar-nav-custom-component.component';

@Component({
  selector: 'app-vessels',
  templateUrl: './vessels.component.html',
  styleUrls: ['./vessels.component.scss']
})
export class VesselsComponent implements OnInit {

  constructor(private sidebar: SidebarNavCustomComponentComponent) { }

  ngOnInit() {
  }

  loadMenu(){
    alert('lol');
    this.sidebar.loadNew();
  }

}

**Comment by g0su** [comment]
@tsegato put your code in "```"  "```" and it will be formatted [format code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/) You should write a service to communicate between components

**Comment by patrickpaip** [comment]
Just change the following code under fesm5 with filename coreui-angular.js at the coreUI module
from ng-template to div

 [{
                    selector: 'app-sidebar-nav',
                    template: "\n    <ul class=\"nav\">\n   <div *ngFor=\"let navitem of navItems\">\n      <li *ngIf=\"isDivider(navitem)\" class=\"nav-divider\"></li>\n        <ng-template [ngIf]=\"isTitle(navitem)\">\n          <app-sidebar-nav-title [title]='navitem'></app-sidebar-nav-title>\n        </ng-template>\n        <ng-template [ngIf]=\"!isDivider(navitem)&&!isTitle(navitem)\">\n          <app-sidebar-nav-item [item]='navitem'></app-sidebar-nav-item>\n        </ng-template>\n      </div>\n    </ul>"
                },] },
    ];

and apply the same for coreui-angular.metadata.json

**Worked for me!**
