### ISSUE TITLE
default-layout.module missing? how/here can i import modules for the default-layout?

### ISSUE THREAD

**Issue by mentadev** [coreui/coreui-free-angular-admin-template#109]
Since there's no default-layout.module, how or where can I import 3rd party modules such as SelectModule so they can be displayed in the default-layout.component.html? 
In my particular case I need to add a ng2-select to the navbar of the default-layout.component.html but I don't know where can I import the required modules:
import { FormsModule } from '@angular/forms';
// Ng2-select
import { SelectModule } from 'ng-select';

Any ideas?

**Comment by tjbartram** [comment]
Hi Mentadev,

I'm having the exact same issue, did you ever find a solution?

Thanks,

**Comment by xidedix** [comment]
hi @tjbartram @mentadev 
afaik at the moment, you have to import required modules in `app.module`

**Comment by mentadev** [comment]
Ok, I'll give it a try. Thanks for the info.
