### ISSUE TITLE
Parent route of children routes shows an empty screen

### ISSUE THREAD

**Issue by tbadlov** [coreui/coreui-free-angular-admin-template#110]
Hello, when opening a route tone level up you see an empty page. 
See this example:
https://coreui.io/angular/demo/#/buttons/buttons
![image](https://user-images.githubusercontent.com/4186587/45334117-65cc6680-b547-11e8-813d-b26bfbb8c75b.png)

vs.
https://coreui.io/angular/demo/#/buttons
![image](https://user-images.githubusercontent.com/4186587/45334133-77ae0980-b547-11e8-87ce-e24afac7bd39.png)

the first url render the buttons component properly, the second url shows an empty page. Is there a way to get around this?

Thanks.

**Comment by ZihangQi** [comment]
try this in buttons-routing.module.ts:

const routes: Routes = [
  {
    path: '',
    data: {
      title: 'Buttons'
    },
    children: [
      **{
        path: '',
        redirectTo: 'buttons'
      },**
      {
        path: 'buttons',
        component: ButtonsComponent,
        data: {
          title: 'Buttons'
        }
      },
      {
        path: 'dropdowns',
        component: DropdownsComponent,
        data: {
          title: 'Dropdowns'
        }
      },
      {
        path: 'brand-buttons',
        component: BrandButtonsComponent,
        data: {
          title: 'Brand buttons'
        }
      }
    ]
  }
];

**Comment by xidedix** [comment]
fixed with template `v2.2.1`
