### ISSUE TITLE
Dynamically adding or removing sidebar menus

### ISSUE THREAD

**Issue by tsegato** [coreui/coreui-free-angular-admin-template#113]
I am trying to add and remove items from the sidebar.

This is my navItems:

export const navItems = [
  {
    name: 'Dashboard',
    url: '/dashboard',
    icon: 'icon-speedometer'
  },
  {
    name: 'Vessels',
    url: '/vessels',
    icon: 'fa fa-ship'
  },
  {
    name: 'Test',
    url: '/test',
    icon: 'icon-speedometer'
  }
];

This is how I add new items:

      var navItemsGroups =    {
        name: 'Assets',
        url: '',
        icon: 'icon-puzzle',
        children: [        
          ]
        };

      data.forEach(element => {
        navItemsGroups.children.push(
          {
            name: element.name,
            url: '/base/cards',
            icon: 'icon-wrench'
          });
      });

      navItems.push(navItemsGroups);

This works as expected. However when I remove items from the array the UI is not updating:
    const index = navItems.map(e => e.name).indexOf('Assets');
      if (index !== -1) {
        navItems.splice(index-1, 1);
      }

Is this a bug, or am I using a wrong approach? How do you add and remove items from the sidebar dynamically?

**Comment by tsegato** [comment]
I created a custom navbar. Feel free to close this.

**Comment by alexander-myltsev** [comment]
@tsegato how did you do this? 

I need to translate sidebar dynamically. It is desirable to achieve it with http://ngx-translate.com . How to do it?
