### ISSUE TITLE
Release on NPM

### ISSUE THREAD

**Issue by lscorcia** [coreui/coreui-free-angular-admin-template#115]
Hello,
according to changelog this project is at release 2.0.1, but the Angular template on npm, used also by the demos, is stuck at 2.0.0-rc1 (https://www.npmjs.com/package/@coreui/angular).

Do you plan to bring it up to date?

Thanks in advance,
Luca

**Comment by xidedix** [comment]
hi @lscorcia 
@coreui/angular has been updated to `v2.2.0` and `Angular 7`
