### ISSUE TITLE
Login/Register components are not vertically centered

### ISSUE THREAD

**Issue by lscorcia** [coreui/coreui-free-angular-admin-template#116]
As demonstrated in the bootstrap component, the login/register boxes should be vertically centered in the browser viewport. Except they are not in this Angular component, rather they get some kind of asymmetric spacing caused by issue https://github.com/coreui/coreui-angular/issues/25.

Fixing that issue with its related pull request exposes this bug in a more visible way.

**Comment by xidedix** [comment]
Hi @lscorcia, thanks for the heads up.
please update `@coreui/angular` to `^2.2.1`

**Comment by lscorcia** [comment]
Issue fixed in version 2.2.1. Thanks for your help @xidedix. 
PS: The online web demo at https://coreui.io/angular/demo/ needs to be updated too.

Have a great day.
