### ISSUE TITLE
Documentation outdated: hide aside menu class

### ISSUE THREAD

**Issue by alexander-myltsev** [coreui/coreui-free-angular-admin-template#119]
I'm using CoreUI Angular. 

https://coreui.io/docs/layout/overview/ says there is `.aside-menu-hidden`. But I don't see any:

![image](https://user-images.githubusercontent.com/574267/48221844-2a61e300-e3a4-11e8-83d8-2b252934f668.png)

Seems like documentation is outdated. How to hide aside menu?

**Comment by xidedix** [comment]
@alexander-myltsev thanks for the catch!
visibility of `aside` and `sidebar` is toggled by `aside-menu-*-show` and `sidebar-*-show` respectively

**Comment by alexander-myltsev** [comment]
Do I understand you correctly that applying `class="aside-menu-show"` to `<app-aside/>` should hide the `aside` menu? If yes, then it doesn't work.

**Comment by alexander-myltsev** [comment]
OK, that works. I was asking if it is possible to make it invisible? Like completely disable right triple bar icon.

**Comment by xidedix** [comment]
Try this:
```
<app-header [sidebarToggler]=false [asideMenuToggler]=false>
</app-header>
```

**Comment by alexander-myltsev** [comment]
Thank you! That worked out!

**Comment by swathibhe** [comment]
Thank you So much.

**Comment by andrrssjarken** [comment]
Hi! The [asideMenuToggler]=false solution does not work when window is resized? Then the MenuToggler returnes. Under 992px width.

**Comment by codekeyz** [comment]
I added this same stuff, asidemenutoggler is gone in large view but appears when i go into mobile view. Any way i can take it off totally ?
```html5
<app-header [asideMenuToggler]=false>
</app-header>
```

**Comment by xidedix** [comment]
hi @codekeyz 
please try:
```html
<app-header 
  [asideMenuToggler]=false
  [mobileAsideMenuToggler]="false" >
</app-header>

**Comment by codekeyz** [comment]
@xidedix thanks, it worked
