### ISSUE TITLE
Initialize app-sidebar minimized

### ISSUE THREAD

**Issue by filipemansano** [coreui/coreui-free-angular-admin-template#120]
How to, set the fixed sidebar (left) to initialize in minimized mode? i tried add the class "brand-minimized sidebar-minimized" in the body tag on index.html but not work

![image](https://user-images.githubusercontent.com/6247393/48640177-04989780-e9bd-11e8-910f-c6137854dd68.png)

**Comment by filipemansano** [comment]
sorry, i found the problem in my tag of sidebar was like this 
`[display]="'sm'"`

i switched to `[display]="'lg'"` and worked!

**Comment by db46** [comment]
Hi @filipemansano - I am trying to achieve the same thing - where did you change the sidebar tag - what file?
Thanks

**Comment by filipemansano** [comment]
> Hi @filipemansano - I am trying to achieve the same thing - where did you change the sidebar tag - what file?
> Thanks

https://github.com/coreui/coreui-free-angular-admin-template/blob/master/src/app/containers/default-layout/default-layout.component.html#L52
