### ISSUE TITLE
app-sidebar-nav navItems reassignment

### ISSUE THREAD

**Issue by nealyip** [coreui/coreui-free-angular-admin-template#126]
```
export class DefaultLayoutComponent implements OnDestroy, OnInit {
       ngOnInit(): void {
        this.navItems = navItems;
        setTimeout(() => {
            this.navItems = [{
                name: 'a',
                url: 'b'
            }];
        }, 3000);
    }
}
```

For the above code, the component will prepend an item instead of replacement.
Is this behavior intended or a bugs?

For semantic meaning, reassigning variables seems to be referring to replacement instead of prepend.

Thanks

**Comment by emilynielson** [comment]
I'm having the same issue. Is there a way to reassign it and get the navbar to only show the reassignment?

**Comment by xidedix** [comment]
@nealyip @emilynielson 
please update `@coreui/angular` dependency to `2.4.0-beta.1`
and let us know if this helps

**Comment by pranavs1791** [comment]
Hi i updated @coreui/angular to @2.4.5 . But still the issue persists. I can't reassign the navItems . The value i change in my .ts  file doesn't get affected in my template file.

**Comment by xidedix** [comment]
hi @pranavs1791 

Please try to use [this code example](https://github.com/coreui/coreui-free-angular-admin-template/issues/126#issue-389014956) for quick and dirty verification whether dynamic reassign of sidebar items works or not.

What you need is to create some sort of sidebar-nav.service to reassign navItems array on the fly and  subscribe the result in default-layout.component
