### ISSUE TITLE
Mobile menu doesn't auto close after navigation to a different route

### ISSUE THREAD

**Issue by moshefi** [coreui/coreui-free-angular-admin-template#13]
It has be closed manually

**Comment by arturpasnik** [comment]
@moshefi Did you manage to find a way to close mobile navigation after navigating to a new route.

**Comment by arturpasnik** [comment]
Update your default-layout.component.ts

and should work.

`import { Component, Input } from '@angular/core';
import { navItems } from './../../_nav';
import { Router, NavigationEnd, Event as NavigationEvent  } from '@angular/router';

@Component({
  selector: 'app-dashboard',
  templateUrl: './default-layout.component.html'
})
export class DefaultLayoutComponent {
  public navItems = navItems;
  public sidebarMinimized = true;
  private changes: MutationObserver;
  public element: HTMLElement = document.body;
  constructor(private router: Router) {

    this.changes = new MutationObserver((mutations) => {
      this.sidebarMinimized = document.body.classList.contains('sidebar-minimized');
    });

    this.changes.observe(<Element>this.element, {
      attributes: true
    });

    router.events.forEach((event: NavigationEvent) => {
      //After Navigation
      if (event instanceof NavigationEnd) {
        this.element.classList.remove('sidebar-show');
      }
    });
  }
}
`
