### ISSUE TITLE
how remove appasidemenutoggler button

### ISSUE THREAD

**Issue by swathibhe** [coreui/coreui-free-angular-admin-template#130]
I don't want to display  aside menu toggler button. But i unable to remove it . Please help me. asap.
Thank you.

code syntax in browser is

<button class="navbar-toggler d-md-down-none" type="button"><span class="navbar-toggler-icon"></span></button>

<button appasidemenutoggler class="navbar-toggler d-lg-none" type="button" ng-reflect-breakpoint><span class="navbar-toggler-icon"></span></button>

**Comment by xidedix** [comment]
hi @swathibhe 
see; https://github.com/coreui/coreui-free-angular-admin-template/issues/119#issuecomment-437703109

**Comment by swathibhe** [comment]
Thank you
