### ISSUE TITLE
rtl style not work correctly

### ISSUE THREAD

**Issue by shomid** [coreui/coreui-free-angular-admin-template#135]
I added `dir="rtl"` to html tag but login page fades.

![screenshot from 2019-01-26 20-21-38](https://user-images.githubusercontent.com/8733354/51790303-7ef94b00-21a8-11e9-9c70-e422f14803f6.png)

**Comment by xidedix** [comment]
hi @shomid 
please update `package.json` dependencies:
- `@coreui/angular` to `^2.2.4`
- `@coreui/coreui`  to `^2.1.6`

and let us know if the issue persists.
