### ISSUE TITLE
Build error in production environment

### ISSUE THREAD

**Issue by sametsafak** [coreui/coreui-free-angular-admin-template#136]
When I try to export project with prod environment (ng build -c=production), it gives this error:

> ERROR in : Unexpected value 'undefined' imported by the module 'AppHeaderModule in /Users/.../Downloads/coreui-free-angular-admin-template-master/node_modules/@coreui/angular/coreui-angular.d.ts'

I try this with clean repository and 2 different computers.

-- 

**Update:** It is working on previous version @coreui/angular **v2.2.3** but not in current **v2.2.4**

**Comment by xidedix** [comment]
hi @sametsafak thanks for the heads-up!
we are investigating this issue

try to lock `@coreui/angular` on version `2.2.5` (package.json)
```
"@coreui/angular": "2.2.5",
```
then run:
```
npm prune
npm i
npm run build
```
please let us know if this workaround helps

**Comment by sametsafak** [comment]
Hi @xidedix

Your solution is also working like v**2.2.3**,

Thank you.
