### ISSUE TITLE
Require indentation for items of left navbar as per its level

### ISSUE THREAD

**Issue by idris-rampurawala** [coreui/coreui-free-angular-admin-template#138]
This is a feature/enhancement request:
- Currently, there is not indentation of navbar items, hence not possible to guess the menu level visually.

As a workaround, I have added some css to add padding to navbar items upto 2 levels of menu:
```.sidebar .nav-dropdown > .nav-dropdown-items > .nav-item > .nav-link {
  padding-left: 1.8rem;
}

.sidebar
  .nav-dropdown
  > .nav-dropdown-items
  > .nav-dropdown
  > .nav-dropdown-items
  > .nav-item
  > .nav-link {
  padding-left: 2.8rem;
}
```

- It would be great if it is added dynamically while building the navbar.

**Comment by xidedix** [comment]
hi @idris-rampurawala 
you can customize default styling in `src/scss/_custom.scss`

**Comment by idris-rampurawala** [comment]
@xidedix Hi, thanks for the reply. Just wanted to understand that the css which I have shared above it the correct way to handle this? Also, by default, there should be some defined indentation in navbar so understand tree hierarchy of links.

**Comment by zhaydexxa** [comment]
you can use this css

`.sidebar .nav-dropdown-items {
  padding-left: 10px;
}`
