### ISSUE TITLE
how to remove chart of coreui ?

### ISSUE THREAD

**Issue by shomid** [coreui/coreui-free-angular-admin-template#139]
I do not need a chart in the my project.
how to remove chart dependencies for my project ?

**Comment by xidedix** [comment]
hi @shomid 
simply remove:
-  `ng2-charts` from `./package.json`
- `ChartsModule`  from '`src/app/app.module.ts`
- charts entries in `_nav.ts` and `app.routing.ts` respectively, if any
- modify/remove all views/modules  with charts, if any

**Comment by shomid** [comment]
hi @xidedix
also remove chart.min.js of angular.json.

thanks
