### ISSUE TITLE
Question about moving children out of elements and remark about non ES6 syntax

### ISSUE THREAD

**Issue by Tekorius** [coreui/coreui-free-angular-admin-template#14]
![image](https://user-images.githubusercontent.com/17677026/31078290-2d0994ec-a78a-11e7-89b8-e14ae3791444.png)

Now we have this in all app components.

My question, is there a reason behind moving children out of the element and then removing that element? This seems detrimental to the initial performance (while the idea may have been to make a dom tree more shallow for future performance, correct me if I'm wrong) 

---

Also, linter immediately complains about these things (these are just some remarks, I'm not complaining):

- If you are using ngOnInit() in the component, the class must implement OnInit interface
- All component class names must be suffixed with Component
- If variables are not reassigned, you should use const instead of var (actually, you should never use var nowadays)

So, I fixed up the class and ended up with this:
![image](https://user-images.githubusercontent.com/17677026/31078545-39c9bcc4-a78b-11e7-92ef-41cc62b33af6.png)

**Comment by mrholek** [comment]
Thank you for your feedback. We use this because we face problems with angular tags and flex layout.

We improve this functions in next release.

**Comment by andreavitali** [comment]
In release 1.0.2 the ngOnInit() function was removed in the components, but styles was not updated, so now the layout is pretty messed up. That because the parent of component with flex layout (for example app-footer) has not `display: flex` property.

**Comment by Tekorius** [comment]
I briefly checked the diff of the latest commit and it seems to be moving in the right direction. I will try to pull the seed project and check it out my self in a couple of days.
