### ISSUE TITLE
how to add router link in angular 6 with coreui

### ISSUE THREAD

**Issue by swathibhe** [coreui/coreui-free-angular-admin-template#141]
Hi, Please help me to solve i want to add router link to the our navbar image icon. how can get this please help me to solve .
navbarBrandFull and navbarBrandMinimized image icon i have to add the routerlink please help me.
![screenshot from 2019-02-22 18 23 17](https://user-images.githubusercontent.com/46274684/53243787-fc907800-36ce-11e9-90bb-821f995aad3e.png)

**Comment by xidedix** [comment]
hi @swathibhe 
go to `/src/app/containers/default-layout/default-layout.component.html`
and add `navbarBrandRouterLink` to `app-header` like thie:

```html
<app-header [navbarBrandRouterLink]="['/dashboard']"  ... >
```

it should work with `@coreui/angular` version `^2.4.2`

**Comment by swathibhe** [comment]
Thank you so much it is working .
