### ISSUE TITLE
dynamically adding and removing sidebar menu based on admin role

### ISSUE THREAD

**Issue by swathibhe** [coreui/coreui-free-angular-admin-template#143]
Hi,
Please help to solve this problem asap.
I am using angular 6 and  coreui/angular to `^2.4.3`
 Based on admin role i have to change the _nav.ts data dyamically.
I have 5 roles in admin using this combination of more than one role, single role and all roles based on this i have to display the sidebar menu.
How to i solve this problem . Please help me

**Comment by xidedix** [comment]
Hi @swathibhe 
_nav.ts returns a plain simple js object to populate sidebar-nav
you can write an agular service to set up dynamically altered copy of this nav config object

**Comment by swathibhe** [comment]
Hi,
I added the dynamically in service file. side menu works correctly but i can not understand how to add this in routing file.
Please look in to this.

**Comment by xidedix** [comment]
@swathibhe 
Your sidebar nav service works for the sidebar menu according to a user specific role. Standard user can't see admin menu entries and that's fine. But the admin area is still available using the address bar. That's why we need to use [route guards](https://angular.io/guide/router#milestone-5-route-guards) and restrict access to some features depending on user role.

**Comment by fgenao-cuore** [comment]
could you share how you dynamically adding and removing sidebar menu?

**Comment by swathibhe** [comment]
Hey, thanks for the response. I got the solution it's completed.

**Comment by fgenao-cuore** [comment]
Where I can see you solution?

*Fernando Genao*
Email: fgenao@cuoregroup.com

**Comment by vvp45** [comment]
@swathibhe Can you help me in the side-nav bar, hide menu after user login. I am in new in angular

**Comment by swathibhe** [comment]
Hey, Okay sure where you stuck let me know

**Comment by Megha-008** [comment]
Hi,
The sidebar loads only after login,how to make it load on every page,based on the page click i need to change the sidebar in coreui.

**Comment by xidedix** [comment]
Hi @Megha-008 

> _nav.ts returns a plain simple js object to populate sidebar-nav
> you can write an angular service to set up dynamically altered copy of this nav config object

**Comment by ngingihy** [comment]
Hi i'm trying to mimic the _nav.ts by creating a service that subscribe to my backend

  public navItems: INavData[]

 getNav(){
   this.navItems = this.dynservice.getNavItem()
}

but nothing is reflected on the navbar, what should i do?
