### ISSUE TITLE
How to Remove flag-icon-css completely?

### ISSUE THREAD

**Issue by AbdulBasitKhaleeq** [coreui/coreui-free-angular-admin-template#144]
I do not need flag-icon-css icons in my prod. whenever i build this theme for production i get all icons as svg files in dist folder. I do not need them at all.
I tried removing "flag-icon-css": "^3.2.1" from package.json file and deleted its saved folder from ng_modeules folder. after build it show error like "can't resolve flag-icon-css in icon linear something like this."

**Comment by ikbal1989** [comment]
remove it from angular.json, then packages.json
-> npm install
-> ng build

**Comment by xidedix** [comment]
and `npm prune`
