### ISSUE TITLE
Sidebar and Aside Menu response and animate laggy on sample page with Charts

### ISSUE THREAD

**Issue by AidanliCD** [coreui/coreui-free-angular-admin-template#145]
Not sure if anyone experiences the same. 

When running this free template site locally, on the pages with Charts (Dashboard/Chart) the side bar and aside menu response on menu button click with significant delay and the slide in/out transition appear really laggy.

These angular demo pages appear nice and smooth on the official site tho.

Any idea? Please help.

Thanks.
Aidan

P.S. locally run the Boostrap and Reactjs free version templates are fine on the Charts page and generally response smoother, but this Angular verion.

**Comment by xidedix** [comment]
hi @AidanliCD 
We are experiencing laggy charts animation on `ng serve` as well. 
The issue goes away on production build. 
Please let us know if this is the case for you.

**Comment by mustafa5253** [comment]
Facing the same issue while running locally, please let me know how to resolve it on local env.


Thanks 
Mustafa

**Comment by amitdixit** [comment]
No even on Production build its still lagging.

**Comment by therrax** [comment]
Tested, sidebar is lagging even on production (locally and on the server, if component contains chart or widget with small chart)
The fact is, on production it has little better performance. To survive but it would be nice if it did not lag

**Comment by treiero** [comment]
Any solution?
Same problem here.

**Comment by xidedix** [comment]
Hi, 

As a temp workaround try to override scss variable `$layout-transition-speed` like:  

- src/scss/_variables.scss
```scss
// Variable overrides
$layout-transition-speed: .02s;
```

**Comment by treiero** [comment]
> Hi,
> 
> As a temp workaround try to override scss variable `$layout-transition-speed` like:
> 
> * src/scss/_variables.scss
> 
> ```css-scss
> // Variable overrides
> $layout-transition-speed: .02s;
> ```

Thanks, that solves for a while.
