### ISSUE TITLE
Can't find components source file

### ISSUE THREAD

**Issue by brunosobsil** [coreui/coreui-free-angular-admin-template#146]
I can't find components file in coreui-angular, only components.d.ts.
For example, in: "node_modules/@coreui/angular/lib/sidebar" There are only component.d.ts files.
Where can I find the app-sidebar-component.ts.

Thanks

Bruno

**Comment by xidedix** [comment]
hi @brunosobsil 
if you need source code for coreui components, please take a look at
https://github.com/coreui/coreui-angular
ex: 
https://github.com/coreui/coreui-angular/tree/master/projects/coreui/angular/src/lib/sidebar
