### ISSUE TITLE
How do I add a Tooltip on App-sidebar-nav item and the title itself?

### ISSUE THREAD

**Issue by hirocsingh** [coreui/coreui-free-angular-admin-template#158]
<app-sidebar [fixed]="true" [display]="'lg'">
    <app-sidebar-nav  [navItems]="navItems" [perfectScrollbar] [disabled]="sidebarMinimized" >
    </app-sidebar-nav>
    <app-sidebar-minimizer></app-sidebar-minimizer>
  </app-sidebar>

Separate tooltip for each item.

**Comment by xidedix** [comment]
As a workaround you can add the html `title` attribute to `src/app/_nav.ts` like this:
```js
export const navItems: INavData[] = [
  {
    name: 'Dashboard',
    url: '/dashboard',
    icon: 'icon-speedometer',
    attributes: { title: 'Dashboard tooltip'}
  },
```

**Comment by angelcuenca** [comment]
@xidedix solution works perfectly.
