### ISSUE TITLE
How to make a dynamic sidebar menu?

### ISSUE THREAD

**Issue by hleder-web** [coreui/coreui-free-angular-admin-template#161]
im trying to use use a json on the place of nav.ts to make the nav itens dynamic depending on the user, but i dont know how can i do it.

interface NavAttributes {
  [propName: string]: any;
}
interface NavWrapper {
  attributes: NavAttributes;
  element: string;
}
interface NavBadge {
  text: string;
  variant: string;
}
interface NavLabel {
  class?: string;
  variant: string;
}

export interface NavData {
  name?: string;
  url?: string;
  icon?: string;
  badge?: NavBadge;
  title?: boolean;
  children?: NavData[];
  variant?: string;
  attributes?: NavAttributes;
  divider?: boolean;
  class?: string;
  label?: NavLabel;
  wrapper?: NavWrapper;
}

export const navItems: NavData[] = [
 ---------json here--------------

];

**Comment by xidedix** [comment]
Hi @hleder-web 
Please take a look here: #143

**Comment by Hagith** [comment]
The easiest option is to create an `Observable` which emits current sidebar items depending on your custom logic. Example:

`sidebar-service.ts`
```typescript
@Injectable()
class AppSidebarService {
  items$: Observable<INavData[]>;

  constructor(private user: UserService) {
    this.items$ = this.user.state$.pipe(
      map(user => this.getSidebarItems(user)),
    );
  }

  private getSidebarItems(user: User): INavData[] {
    // logic depending on user context
    return [ /* sidebar items */];
  }
}
```

`sidebar.html`
```html
<app-sidebar-nav [navItems]="sidebar.items$ | async"></app-sidebar-nav>
```

**Comment by RNKushwaha022** [comment]
How `sidebar.items$`  is available in html? In my case it says `Property 'sidebar' does not exist on type 'DefaultLayoutComponent'`.
