### ISSUE TITLE
Issue routing to a component when manually typing the url on address bar

### ISSUE THREAD

**Issue by ngajugodwin** [coreui/coreui-free-angular-admin-template#162]
Guys,

Please, there’s something strange going on.

I created users component which shows the list of users, I have a button which is used to navigate to => localhost:4200/users/new. Now, everything works really fine when I click on the button as this navigate the new component. But when I manually type => localhost:4200/users/new on the address bar, it throws up a runtime error without displaying the requested page.

Here is how I’ve setup so far.

AppRoute 
```
 { path: '', component: DefaultLayoutComponent, data: { title: 'Home' },
    children: [
      {
        path: 'users',
       loadChildren: () => import('./views/post-login/users/users.module').then(m => m.UsersModule)
      },
}
```

UsersRoutingModule
```
const routes: Routes = [
  { path: '', component: UsersComponent, data: { title: 'Users' } },
  { path: 'new', component: UserFormComponent }
];

@NgModule({
  imports: [RouterModule.forChild(routes)],
  exports: [RouterModule]
})
export class UsersRoutingModule {}
```

UsersModule
```
@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    UsersRoutingModule,
    // BsDropdownModule.forRoot()
  ],
  declarations: [
      UsersComponent,
      UserFormComponent
    ]
})
export class UsersModule { }
```

I got this error on console without any display on page =>
`GET http://localhost:4200/users/new/runtime.js net::ERR_ABORTED 404 (Not Found)`
 
Normally, i was expecting it to show me the 404 page, because whenever i typed an invalid url, it routes to that page.

Any help on how to go about this will be appreciated.

**Comment by ngajugodwin** [comment]
I was able to figure out how to solve this. Thanks!

**Comment by gianlucainnocente** [comment]
@ngajugodwin i have the same problem. How did you resolve that?
