### ISSUE TITLE
Header, Footer and sidebar does not display on created new page 

### ISSUE THREAD

**Issue by ashishinnotec** [coreui/coreui-free-angular-admin-template#166]
I have created new view page users using following command.

ng generate component views/users
ng generate module views/users--routing=true

I got following files from above commands

1) users.component.css
2) users.component.html
3) users.component.spec.ts
4) users.component.ts
5) users.module.ts
6) users-routing.module.ts

I have set the routing in _nav.ts
{
    name: 'Users',
    url: '/users',
    icon: 'icon-pencil'
  },

And app.routing.ts file 

import { UsersComponent } from './views/users/users.component';

 {
    path: 'users',
    component: UsersComponent,
    data: {
      title: 'Users'
    }
  },

When I redirecting to users. i did not get header ,sidebar and footer
![image](https://user-images.githubusercontent.com/55989470/70845185-82a1c900-1e71-11ea-8a58-518dbb1fe88d.png)

**Comment by xidedix** [comment]
Hi @ashishinnotec 
It looks you've: 
- missed default layout
- imported component instead of users module

`app.routing.ts` file:
```js
export const routes: Routes = [
  {
    path: '',
    component: DefaultLayoutComponent,
    data: {
      title: 'Home'
    },
    children: [
      {
        path: 'users',
        loadChildren: () => import('./views/users/users.module').then(m => m.UsersModule)
      },
```
