### ISSUE TITLE
More than one custom value accessor matches form control with unspecified name attribute

### ISSUE THREAD

**Issue by vinaykarora** [coreui/coreui-free-angular-admin-template#167]
I am creating an application using angular8.

**Current behavior**
I need to get a autocomplete textbox from user input using a bootsrap typeahead (ngbTypeahead), but when I put a [(ngModel)]="model" and [ngbTypeahead]="search" attribute on user input.

If I remove  [(ngModel)]="model" on input field it work's but first matched value filled in the input field . But I add [(ngModel)]="model" to work as expected I got following error:

```Error: Uncaught (in promise): Error: More than one custom value accessor matches form control with unspecified name attribute```

**Expected behavior**
The input field should autocomplete based on user input.
https://stackblitz.com/run?file=app/typeahead-prevent-manual-entry.ts

I am using bootstrap modules that I got from web ng-bootstrap.

**Comment by shashikantu7** [comment]
@vinaykarora , I am facing same issue in angular 2 when I am using <div [(ngmodel)]="model" contenteditale="true" [editorfunction]></div>
