### ISSUE TITLE
Angular-playground does not compile inside coreui project

### ISSUE THREAD

**Issue by catasoft** [coreui/coreui-free-angular-admin-template#173]
Hello,

I installed the coreui-free-angular-admin-template, and then wanted to add the angular-playground component, which is not compiling. 
```
ng add angular-playground
npm run playground
```
Result: 

> ERROR in getInternalNameOfClass() called on a non-ES5 class: expected UrlService to have an inner class declaration.

This is quite a deal-breaker.
Thanks,
Catalin

**Comment by xidedix** [comment]
Hi @catasoft 
It looks like it has sth to do with `Ivy` engine, I am afraid. See: https://github.com/SoCreate/angular-playground/issues/235  
Have you tried to disable Ivy?
- in `angular.json` set `"aot": false;`
- in `tsconfig.app.json` in the `angularCompilerOptions` set `"enableIvy": false`

**Comment by ddehghan** [comment]
yes. disabling Ivy is getting rid of this error for us. still need to figure out what is causing this.
