### ISSUE TITLE
[Angular] -> zone.js:1810 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by felipelc454** [coreui/coreui-free-angular-admin-template#177]
hello i'm having the problem, i'm using Coreui Angular...
zone.js:1810 [Violation] Added non-passive event listener to a scroll-blocking 'wheel' event. Consider marking event handler as 'passive' to make the page more responsive.

**Comment by xidedix** [comment]
Hi @felipelc454 

Thanks for the heads-up. 
This is a perfect-scrollbar issue actually and, it generates a warning to the console (chromium). 
See: https://github.com/mdbootstrap/perfect-scrollbar/issues/560

**Comment by felipelc454** [comment]
In short, is there no solution to this problem?

**Comment by xidedix** [comment]
@felipelc454 
Help wanted.
We'll see what we can do about it anyway.

**Comment by felipelc454** [comment]
@xidedix Ok thank you very much, I'll be waiting
