### ISSUE TITLE
Change icon provider in app-sidebar-nav

### ISSUE THREAD

**Issue by Codem3ay** [coreui/coreui-free-angular-admin-template#179]
I want to use another icon provider like font-awesome for my nav-link, I changed the icon in the _nav.ts file but it doesn't seem to work. How can I achieve such behavior? Thanks

**Comment by xidedix** [comment]
Hi, @Codem3ay 
what about:
```js
  {
    name: 'Dashboard',
    url: '/dashboard',
    icon: 'fa fa-telegram',
  },
```
