### ISSUE TITLE
Open only one item in app-sidebar

### ISSUE THREAD

**Issue by HakamFostok** [coreui/coreui-free-angular-admin-template#181]
Is there a way to open just one expand only one element in the app-sidebar,
I want the close the open dropdown button when the user clicks on another dropdown button.
so I want to establish the effect that only one dropdown can be opened in the app-sidebar at any given time.

in the following image, I show my problem I can open two of a dropdown button at the same time, and this is not the desired behavior for me

![image](https://user-images.githubusercontent.com/12747172/76941662-79f7dd80-690d-11ea-8200-ea107305d981.png)

Thanks in advanced

**Comment by KevinGarciaJ** [comment]
Hello, were you able to complete this task?

**Comment by HakamFostok** [comment]
It was long ago I do not remember I am really sorry
