### ISSUE TITLE
[question] Downgrade to Angular 8

### ISSUE THREAD

**Issue by pmirandaarias** [coreui/coreui-free-angular-admin-template#188]
It's possible to use CoreUI with Angular 8? is there any commit that has Angular 8 version?

**Comment by xidedix** [comment]
What about template [v2.5.3](https://github.com/coreui/coreui-free-angular-admin-template/releases/tag/v2.5.3)? You can also try to use it with @coreui/angular v2.9.2 and typescript v3.6
