### ISSUE TITLE
How to change BADGE'S TEXT in Side NavBar  dynamically

### ISSUE THREAD

**Issue by Resington** [coreui/coreui-free-angular-admin-template#190]
Hi, Can anyone please help me to changing the Badge's text present in _nav.ts file dynamically.  I have to fetch the dynamic text from database sever through httpclient, which i can do that. Thanks in advance...

export const navItems: INavData[] = [
  {
    name: "Dashboard",
    url: "/dashboard",
    icon: "icon-speedometer",
     badge: {
       variant: 'info',
       text: 'NEW'   // <<<< THIS IS THE TEXT, I WOULD LIKE TO CHANGE
     }
  },
....

**Comment by MELAS007** [comment]
Could you put your solution please? I am facing the same issue!
Thanks in advanced!

**Comment by Sanafan** [comment]
Same here still no solution....
