### ISSUE TITLE
 Cannot find module '../../dist/@coreui/angular

### ISSUE THREAD

**Issue by sunn789** [coreui/coreui-free-angular-admin-template#193]
after ng serve  I got this error 

        `ERRORin src/app/_nav.ts:1:26 - error TS2307: Cannot find module '../../dist/@coreui/angular'.

     1 import { INavData } from '../../dist/@coreui/angular';
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     src/app/app.module.ts:29:8 - error TS2307: Cannot find module '../../dist/@coreui/angular'.

     29 } from '../../dist/@coreui/angular';
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~` #

**Comment by juliankgp** [comment]
use this
import { INavData } from '@coreui/angular';

**Comment by aishwaryapusarla-saven** [comment]
no i am still getting the same error in app.module.ts

**Comment by JeanWendell** [comment]
Install in the following sequence:

$ npm install @coreui/angular --save
$ npm install -g @angular/cli
$ npm install
$ npm serve -o

**Comment by Newan** [comment]
> no i am still getting the same error in app.module.ts

import {
  AppAsideModule,
  AppBreadcrumbModule,
  AppHeaderModule,
  AppFooterModule,
  AppSidebarModule,
} from  '@coreui/angular';
