### ISSUE TITLE
ERROR in multi ./node_modules/@coreui/icons/css/coreui-icons.css 

### ISSUE THREAD

**Issue by JACLEMGO** [coreui/coreui-free-angular-admin-template#198]
Config:
Angular CLI: 9.1.12
Node: 10.15.3
OS: darwin x64
Angular: 9.1.12

ERROR in multi ./node_modules/@coreui/icons/css/coreui-icons.css ./node_modules/flag-icon-css/css/flag-icon.css ./node_modules/font-awesome/css/font-awesome.css ./node_modules/simple-line-icons/css/simple-line-icons.css ./src/scss/style.scss

Module not found: Error: Can't resolve '/XXXXX/web-app/node_modules/simple-line-icons/css/simple-line-icons.css'

**Comment by xidedix** [comment]
@JACLEMGO see: https://github.com/coreui/coreui-free-angular-admin-template/issues/196

**Comment by JACLEMGO** [comment]
thanks @xidedix
