### ISSUE TITLE
Trying to use sidebar alone

### ISSUE THREAD

**Issue by alwinaugustin** [coreui/coreui-free-angular-admin-template#202]
I am trying to  use the sidebar from coreui in one of the admin interface that I have created. I have added the following npm modules:

1. @coreui/coreui
2. @coreui/angular

and including the following stylesheet. 

`
_node_modules/@coreui/coreui/dist/css/coreui.min.css_`

Then I am including the following to the app module file. 

```
import {
  AppAsideModule,
  AppBreadcrumbModule,
  AppHeaderModule,
  AppFooterModule,
  AppSidebarModule,
} from '@coreui/angular';

 imports: [
        CommonModule,
        HttpClientModule,
        HttpClientJsonpModule,
        RouterModule,
        FormsModule,
        AppAsideModule,
        AppBreadcrumbModule,
        AppHeaderModule,
        AppFooterModule,
        AppSidebarModule,
    ],
```
Now I am using following HTML element in template:

```
<app-sidebar #appSidebar [fixed]="true" [display]="'lg'" [minimized]="sidebarMinimized" (minimizedChange)="toggleMinimize($event)">
    <app-sidebar-nav [navItems]="navItems"></app-sidebar-nav>
    <app-sidebar-minimizer></app-sidebar-minimizer>
  </app-sidebar>
```
But I have the following problems.

1. It is not displaying sidebar correctly. It only shows the navigation items.
2. The style is not applied.

I am using this on Angular 10 version. Is it possible to use only one item like this ?

I have copied the entire style file and pasted it to the component stylesheet, but then also it is not working. 

The sidebar appears like the following:

**Comment by xidedix** [comment]
@alwinaugustin please try to keep following structure:

```html
<body class="app sidebar-fixed sidebar-show">
  <div class="app-body">
    <app-sidebar>
      <app-sidebar-nav></app-sidebar-nav>
      <app-sidebar-minimizer></app-sidebar-minimizer>
    </app-sidebar>
     ...
  </div>
</body>
```

**Comment by rkraghavendra** [comment]
@alwinaugustin  if you are using @coreui/coreui version 3 or greater then try to downgrade it to 2.1.16 its worked for me
