### ISSUE TITLE
Not able to build from Master or Email Zip Download

### ISSUE THREAD

**Issue by lelong37** [coreui/coreui-free-angular-admin-template#210]
We're unable to do npm install for both repo and Zip download:

![image](https://user-images.githubusercontent.com/4691404/122796263-cace5280-d283-11eb-885e-dfdd0623b91a.png)

Please help.

**Comment by Bykiev** [comment]
@lelong37, hi!

There is smth wrong with dependencies, you can try

`npm install --force`

**Comment by pawiromitchel** [comment]
I'm also facing the same issue, using `npm i --legacy-peer-deps` did fix it. I don't know if this would be bad in the long run

**Comment by BelvedereHenrique** [comment]
On package.json, changing from
`    "karma-jasmine-html-reporter": "^1.5.0",`
to
`    "karma-jasmine-html-reporter": "~1.5.0",`
 works for me.

**Comment by krishnadaspalode** [comment]
If you are using any latest node versions, update below devDependencies in package.json file

"jasmine-core": "~3.8.0",
"karma-jasmine-html-reporter": "^1.6.0",

and do rum 'npm install'. It will work for sure!!!
