### ISSUE TITLE
CoreUI 4 and Angular 12  support

### ISSUE THREAD

**Issue by Bykiev** [coreui/coreui-free-angular-admin-template#211]
@xidedix, hello!

Thank you for you hard work and nice-looking template. Is any plans to support CoreUI 4 and upgrade template to use with latest angular version?

**Comment by Codem3ay** [comment]
Any news?

**Comment by xidedix** [comment]
We're at CoreUI 4 and Angular 13. 
Here you go: 
- https://github.com/coreui/coreui-free-angular-admin-template/releases/tag/4.0.0-alpha.3
- https://coreui.io/angular/docs/4.0/

**Comment by MuhKuh7** [comment]
@xidedix, thx for the update. When do you plan to release the final version?

**Comment by Bykiev** [comment]
@xidedix, is any estimates when the final release will be available?

**Comment by xidedix** [comment]
The v4 seems stable, we are not going to make api changes at the moment. Just enhancements.
We'd appreciate any feedback you can give us on this.
