### ISSUE TITLE
Migration guide from 2.x to 4.x

### ISSUE THREAD

**Issue by Bykiev** [coreui/coreui-free-angular-admin-template#218]
Hi,

I love your templates very much, but there are a lot of difference since v2 and migration guide will be very handy. For ex., there is no more ngx-bootstrap, which was replaced with coreUI components. Can you please make it for smooth update?

**Comment by hamz4arif** [comment]
yes..we need better documentation for the migration from the old to the latest version

**Comment by foramkumar-parekh** [comment]
Hi @mrholek @xidedix 
We need this documentation, to better take care of all the changes
