### ISSUE TITLE
Side menu items isn't closed accordingly 

### ISSUE THREAD

**Issue by ahmedsamirbek** [coreui/coreui-free-angular-admin-template#222]
I have issue here I need when open menu group item others collapsed

**Comment by ahmedsamirbek** [comment]
@xidedix I need , when open one other closed

**Comment by pabloinforio** [comment]
Any solution? I see that the vue version (https://coreui.io/vue/docs/3.2/components/sidebar.html) has the prop <b>dropdownMode</b> with value <b>closeInactive</b>. "closeInactive - closes every inactive dropdown on route change, opens dropdown when route state is active".

**Comment by xidedix** [comment]
@pabloinforio 
CoreUI 4 for Angular  - `closeInactive` prop of SidaberNav is the default value of `dropdownMode`.
It opens SidebarNavGroup - when an active route matches `url` for a navItem with `children` (`navItems: INavData[]`)
It closes every SidebarNavGroup on route change - when an active route does not match `url` for a navItem with `children`

**Comment by pabloinforio** [comment]
@xidedix 
So there's no way to close one group when click in other group? I'm asking because I notice this behavior in vue (https://coreui.io/demos/vue/4.0/free/#/dashboard) and bootstrap (https://coreui.io/demos/bootstrap/4.3/default-v3/) example.

**Comment by xidedix** [comment]
@pabloinforio
Thanks for the clarification.  We'll try to fix the issue in an upcoming patch later next week.

**Comment by xidedix** [comment]
@pabloinforio 
fixed in `@coreui/angular@4.2.14`

`dropdownMode` prop accepts one of the following:
  - `path`: close inactive sidebar-nav-group on active route change only (default - backward compatible)
  - `close`: close open sidebar-nav-group on other group click
  - `none`: keep sidebar-nav-group open
