### ISSUE TITLE
Use CORE UI Angular Forms with reactive forms

### ISSUE THREAD

**Issue by layinka** [coreui/coreui-free-angular-admin-template#225]
Hello,

I am trying to use Reactive forms with the Core UI forms and inputs.

Its working fine except that the whole form loads in the invalid stage and all the form inputs are displaying the errors.

Is there anyway we can use this Form module with Angular Reactive forms?

**Comment by xidedix** [comment]
@layinka please update `@coreui/coreui` dependency to the latest version (v4.1.6 at the moment)

**Comment by layinka** [comment]
Ok, so to clarify

Am i to use version 4.1.6 with the bootstrap validation classes you mentioned? or i should revert back to v4.1.4?

**Comment by layinka** [comment]
OK I understand some of the difference, but my point is that, I can't use 4.1.6 at all since the errors field seems to remain empty for invalid inputs. So no way to display the errors for users to see as is usual with reactive formsBy the way I am using floating label inputs, could that be a factor? -------- Original message --------From: xidedix ***@***.***>Date: Mon, 20 Jun 2022, 19:00To: coreui/coreui-free-angular-admin-template ***@***.***>Cc: layinka ***@***.***>, Mention ***@***.***>Subject: Re: [coreui/coreui-free-angular-admin-template] Use CORE UI Angular Forms with reactive forms (Issue #225)
@layinka it's up to you
v4.1.4 includes angular control status classes and as you noticed, the whole form will load in the invalid stage
v4.1.6 dropped the use of angular control status classes at all

**Comment by xidedix** [comment]
@layinka we're going to add some better examples in the docs later this week, stay tuned

**Comment by xidedix** [comment]
@layinka 
see: https://coreui.io/angular/docs/forms/validation#enhanced-example
yeah, looks overcomplicated

**Comment by layinka** [comment]
yeah, not as straight forward.

but it works fine now ,so Thanks a lot
