### ISSUE TITLE
No Bootstrap support in V4

### ISSUE THREAD

**Issue by foramkumar-parekh** [coreui/coreui-free-angular-admin-template#226]
Hi,

I am trying to use normal bootstrap classes (float-left, ml-auto, etc), but they do not seem to work. 
@mrholek @xidedix  Can you please help me understand if there is a way to make it work with Core UI V4?

**Comment by mrholek** [comment]
@foramkumar-parekh please use `float-start`, `float-end`, `ms-auto`, `me-auto`.
