### ISSUE TITLE
Regarding two way binding in an input field 

### ISSUE THREAD

**Issue by D-And-S** [coreui/coreui-free-angular-admin-template#227]
I m using CORE-UI angular for my project. I got stuck with an issue while doing two-way binding with an input. the problem is whenever I specify two way binding in an input field it appears to be valid by default and apply ng-valid class. I extremely need help to get rid of this issue

Before applying two way binding in an input

 ```
 <input
        cFormControl
        type="text"
        placeholder="Username"
        name="UserName"
    >
```
![1](https://user-images.githubusercontent.com/101009348/178059005-d26b2fe9-d4b1-4cdc-a748-8d96fe892b1c.PNG)

After applying two way binding in an input.  it just render the ng-valid style by default. 

```
 <input
        cFormControl
        type="text"
        placeholder="Username"
        name="UserName"
        [(ngModel)]="model.UserName" <!-- here --!>
    >
```

![2](https://user-images.githubusercontent.com/101009348/178059230-23e0577e-0ee3-480c-a3fd-6a1fa079c599.PNG)

**Comment by xidedix** [comment]
@D-And-S 
please update `@coreui/coreui` to `v4.1.6` or `latest`
let us know if it works for you

**Comment by D-And-S** [comment]
thanks @xidedix .. it worked..
