### ISSUE TITLE
Tooltip flickering and scrollbar flickering

### ISSUE THREAD

**Issue by elemen7s** [coreui/coreui-free-angular-admin-template#228]
OS: Windows 10
Browser: Chrome & Edge
Test case: In demo link - https://coreui.io/demos/angular/4.1/free/#/base/tooltips

When the tooltip is shown for the first time, the elements next to it flicker.

Another issue which might be related, when you quickly hover over the buttons which all have a tooltip, the scroll bar appears and disappears. It's like the extra tooltips not shown on screen are being appended to the bottom.

**Comment by xidedix** [comment]
fixed in @coreiu/angular `v4.2.1`

**Comment by xidedix** [comment]
actually fixed in  @coreiu/angular `v4.2.2`
