### ISSUE TITLE
Not able to create shared component

### ISSUE THREAD

**Issue by RajeshCherukuri** [coreui/coreui-free-angular-admin-template#23]
Hi, I am not able to create a shared component which can be used in multiple views. Here is what I did
1) Created a separate component inside components folder and added this component in index files and app.module
2) I am trying to call that component from an HTML file which is inside a different module which is in views folder.

Here is the error I am receiving. Is that the right place to create a shared component? I did try creating a shared component inside views folder still no luck. Please suggest me where I am doing wrong. Thanks.

<img width="1433" alt="screen shot 2017-10-19 at 10 03 01 pm" src="https://user-images.githubusercontent.com/3213542/31805901-55fd9afa-b519-11e7-8bae-d12791df2251.png">

**Comment by marcelofns** [comment]
I'm not sure, but components of app.module are not available to sub-modules. Have you tried to add the new component to your new component module, to declarations section?
Maybe you need a shared module to hold this: https://angular.io/guide/ngmodule#shared-modules

**Comment by kamal0808** [comment]
Did you try to export that component?
