### ISSUE TITLE
Licensing and fair use

### ISSUE THREAD

**Issue by StefanSCT** [coreui/coreui-free-angular-admin-template#233]
Hello,

We are thinking about using CoreUI Free Angular Template for UI/UX application that will have a backend that is developed in-house, but Licensing models are getting us confused.
The confusion that we are having is about distributing the application to clients.
We would use CoreUI Free Angular Template for an On Cloud Service which would be sold to multiple clients.
Each client would have the same default pages, but they will probably be changed between clients to reflect their corporate colours, field requirements, etc.

Is this covered by the MIT license or would we need to buy Standard or Extended?

If we would need to buy a Licensing model, which one would we need?

What is the pricing model for the Standard and Extended model? All I could find is pricing for Team Bundle and Enterprise Bundle.

**Comment by mrholek** [comment]
Hi, CoreUI Free Angular Template it's MIT licensed product, so you can use it for free in your project.

If you need PRO components, dedicated support, or want to support CoreUI development you can buy a Team license that covers your use case.
