### ISSUE TITLE
Modal Problem

### ISSUE THREAD

**Issue by kernle27** [coreui/coreui-free-angular-admin-template#234]
The Modal in Version 4.2.5 does not show up correctly. If i click once on the button who opens the modal shows only the backdrop. And only i press another input like strg. The modal opens.

**Comment by xidedix** [comment]
@kernle27 do you observe this issue  here? https://coreui.io/demos/angular/4.2/free/#/notifications/modal

**Comment by kernle27** [comment]
![IMG_20221016_213331.jpg](https://user-images.githubusercontent.com/7137215/196054516-d047609f-4239-4f63-bd00-3fc4d98bcd2d.jpg)

Yeah, the problem is , if i click on the button it opens but the animation don't play so it looks like. I only see the backdrop. And after i click control or smthng it opens. Did u have any ideas what i can do?

**Comment by xidedix** [comment]
@kernle27 Could you please check if it works with `@coreui/angular@4.2.3` exact?

**Comment by kernle27** [comment]
@xidedix yes that did work for me. Very nice 👍 Thank you 😊

**Comment by xidedix** [comment]
@kernle27 thanks for pointing this out 👍
