### ISSUE TITLE
Open Modal in an Modal

### ISSUE THREAD

**Issue by kernle27** [coreui/coreui-free-angular-admin-template#235]
Hej is it possible to open a Modal in an other Modal? If i do so the first modal get closed. And cant be reopened. Or should we avoid that? Thank you for your help 🙂

**Comment by xidedix** [comment]
@kernle27 
Nested modals are not supported as they lead to a confusing user experience. 
CoreUI follows Bootstrap and allows only one modal window at a time. 
All in all - this is by design.

**Comment by kernle27** [comment]
Alright Thank you for your fast Response
