### ISSUE TITLE
Cannot find on how to change default to light theme v3

### ISSUE THREAD

**Issue by 32x0lf** [coreui/coreui-free-angular-admin-template#238]
Hi,

We have purchased a pro version and we want the Light V3 theme but we cannot find it. How to change the theme?

Bug reports must include:

- Operating system and version (Windows)

**Comment by mrholek** [comment]
@32x0lf you can download it here - https://coreui.io/download/

**Comment by 32x0lf** [comment]
> @32x0lf you can download it here - https://coreui.io/download/

Thank you
