### ISSUE TITLE
Right to Left language support? 

### ISSUE THREAD

**Issue by delphimaster** [coreui/coreui-free-angular-admin-template#24]
Did your template support Arabic Language which needs to be viewed from Right to Left?

**Comment by ahmadalli** [comment]
yes it does. just set `dir="rtl"` inside `html` tag in you index.html file
```html
<html dir="rtl">
```

**Comment by MoAsmar** [comment]
This doesn't apply mixins for paddings and margins, otherwise is live preview of pro version it's working.

![image](https://user-images.githubusercontent.com/8542126/85210927-42a62c00-b355-11ea-90b1-f117a874b3b0.png)
