### ISSUE TITLE
Need to show nav item name on hover of icon in narrow view

### ISSUE THREAD

**Issue by brijeshpant83** [coreui/coreui-free-angular-admin-template#242]
Note sure if it's a bug of coreUI (4.3.0) with angular 15, however it was available in 9.x version.

Need to show nav item name on hover of icon in narrow view.

<img width="260" alt="Screenshot 2023-01-09 at 4 00 45 PM" src="https://user-images.githubusercontent.com/42262135/211288167-1be17737-1fa5-4044-9899-00d94ac4297f.png">

**Comment by xidedix** [comment]
@brijeshpant83 in CoreUI 4.x for Angular the `narrow` prop works by design only for single level sidebar-nav and it doesn't display item name on hover. You can use `unfoldable` prop instead.
