### ISSUE TITLE
Modal is not disposing off through javascript/typescript

### ISSUE THREAD

**Issue by adnan-atex** [coreui/coreui-free-angular-admin-template#245]
Hi - I am having the same issue. According to Modal API, the hide() method does not work through javascript and the modal not close. Please see the code snippet, and advice - if I am doing something wrong here:

**Hide Modal (Code Snippet):**

```
 <ng-template #staticBackdrop>
    <button [cModalToggle]="staticBackdropModal.id" cButton (click)="onFinishAction()">Finish</button>
    <c-modal #staticBackdropModal backdrop="static" id="staticBackdropModal">
      <c-modal-header>
        <h5 cModalTitle>Download Import Template</h5>
        <button [cModalToggle]="staticBackdropModal.id" cButtonClose></button>
      </c-modal-header>
      <c-modal-body>Download the import template. Are you sure?</c-modal-body>
      <c-modal-footer>
        <button (click)="onCloseModalAction()" cButton color="secondary">
          Close
        </button>
        <button cButton color="primary" (click)="onDownloadAction()">Download</button>
      </c-modal-footer>
    </c-modal>
  </ng-template>
```

**Typescript:**

```
const myModal = new coreui.Modal('#staticBackdropModal', {

})
myModal.dispose();
```

**Comment by xidedix** [comment]
@adnan-atex 

This is Angular version, do not expect it to work with base coreui js. 

The docs: https://coreui.io/angular/docs/components/modal

See also the following examples with ModalService
- https://stackblitz.com/edit/coreui-angular-modal-a2jrujt?file=README.md
- https://stackblitz.com/edit/angular-ivy-fzhi5g?file=src%2Fapp%2Fapp.component.ts

**Comment by adnan-atex** [comment]
This problem has been solved by above suggestion. Thanks for the help.
