### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by cdot65** [coreui/coreui-free-angular-admin-template#247]
This may be intentional, but I noted that this Angular derivative of the CoreUI project is missing its MIT license file.

It's possible that I misunderstood what restrictions the MIT license has, but I believe there is a requirement to maintain the original project's licensing file and copyrights.

**Comment by xidedix** [comment]
Thanks @cdot65 
The readme file contained information about the MIT license.
We just added the missing license file.
