### ISSUE TITLE
collapse other section when one is extended

### ISSUE THREAD

**Issue by lakhank295** [coreui/coreui-free-angular-admin-template#26]
hello i am using your Admin Template & it's a great template. but i am facing one problem while customising your template. you have provided slide bar, where list menu's  present. i want to make that menu collapsible means when i click on a menu that menu should open but other opened menu should close or collapse.

**Comment by mentadev** [comment]
that would be great, all templates have that but this doesn't :( all expanded sections remain expanded even when you open a new section

**Comment by mariomace20** [comment]
how it is possible?, someone have a solution?

**Comment by xidedix** [comment]
This functionality will be introduced in the upcoming CoreUI 3 version.
