### ISSUE TITLE
 Could not find a declaration file for module '@coreui/icons'. 'node_modules/@coreui/icons/dist/cjs/index.js' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by mahmoudmohsendev** [coreui/coreui-free-angular-admin-template#265]
When I run 'npm start' after 'npm install' I got this error >> Could not find a declaration file for module '@coreui/icons'. 'node_modules/@coreui/icons/dist/cjs/index.js' implicitly has an 'any' type.

**Comment by xidedix** [comment]
@mahmoudmohsendev cannot reproduce
What's your version of (see package.json):
- angular
- @coreui/angular
- @coreui/coreui
- @coreui/icons
- @coreui/icons-angular
- nodejs
- typescript?

**Comment by nlitterat** [comment]
the same here
