### ISSUE TITLE
Modal only shows after adding css classes

### ISSUE THREAD

**Issue by bruno-lopes** [coreui/coreui-free-angular-admin-template#266]
Modals were not showing, only the backdrop. I had to set the following styles to make them show:

.modal {
  display: none !important;
}
.modal.show {
  display: block !important;
}

I'm using the following coreui versions:

```
"@coreui/angular": "^5.1.0",
"@coreui/angular-chartjs": "~5.0.0",
"@coreui/chartjs": "~4.0.0",
"@coreui/icons": "^3.0.1",
"@coreui/icons-angular": "^5.0.0",
"@coreui/utils": "^2.0.2",
```

Before opening:

- [Search for duplicate or closed issues](https://github.com/coreui/coreui-free-angular-admin-template/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [Validate](https://html5.validator.nu/) any HTML to avoid common problems
- Read the [contributing guidelines](https://github.com/coreui/coreui-free-angular-admin-template/blob/v4-dev/.github/CONTRIBUTING.md)

Bug reports must include:

- Operating system and version (Windows, macOS, Android, iOS): "Linux Mint 21.3"
- Browser and version (Chrome, Firefox, Safari, Microsoft Edge, Opera, Android Browser): Firefox 126.0
- A [reduced test case](https://css-tricks.com/reduced-test-cases/) or suggested fix using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)

**Comment by xidedix** [comment]
@bruno-lopes cannot reproduce
make sure you've got animations enabled https://coreui.io/angular/docs/5.x/getting-started/introduction#animations
