### ISSUE TITLE
Ask module Remove file, search all file:  inflight, rimaraf, glob

### ISSUE THREAD

**Issue by lenguyen09092k** [coreui/coreui-free-angular-admin-template#271]
Before opening:

PS C:\Users\SenMS\Desktop\src\coreui-free-angular-admin-template-5.2.16> npm i
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

What is the purpose of this Src using these 3 libraries?

![image](https://github.com/user-attachments/assets/2c5ac449-2440-4fb6-af5d-d430513f383f)

**Comment by xidedix** [comment]
@lenguyen09092k You can verify it using the following commands:

```bash
npm ls inflight 
```

```bash
npm ls rimraf
```

```bash
npm ls glob
```

It turns out that Angular's default [karma test runner](https://angular.dev/guide/testing) depends on these packages.

You can also unit-test your Angular application with other testing libraries and test runners.
