### ISSUE TITLE
side menu items in RTL should stick to right

### ISSUE THREAD

**Issue by ahmadalli** [coreui/coreui-free-angular-admin-template#31]
Hi.

Thank you for this great theme.

when I set `dir="rtl"`

![image](https://user-images.githubusercontent.com/2167301/32750480-094b7696-c8d8-11e7-97e3-a716a0e62e0e.png)

this happens in sidemenu: 

![image](https://user-images.githubusercontent.com/2167301/32750437-df6c78ac-c8d7-11e7-9937-71747eaf1f6f.png)

while it's ok in ltr mode:

![image](https://user-images.githubusercontent.com/2167301/32750510-1e38252c-c8d8-11e7-9400-6c94575112a8.png)

the problems are
- items must stick to right (right now they're overlapping arrow icon in items with submenu)
- sidebar minimizer arrow should point and stick to other direction

**Comment by ahmadalli** [comment]
I've fixed the menu item issue. this is my `_rtl.scss` diff:

```diff
diff --git a/src/scss/core/_rtl.scss b/src/scss/core/_rtl.scss
index 28db385..f432df1 100644
--- a/src/scss/core/_rtl.scss
+++ b/src/scss/core/_rtl.scss
@@ -134,6 +134,7 @@
         .nav-item {
           .nav-link {
             direction: rtl;
+            text-align: right;
             i {
               margin: 0 0 0 ($sidebar-nav-link-padding-x / 2);
             }
```

**Comment by ahmadalli** [comment]
I finally fixed both problems. but I don't know where to send PR. Will you apply the PR (if accepted) to other core-ui repositories? @mrholek

**Comment by xidedix** [comment]
Please update to the latest version to `@coreui/coreui`

I'm closing this since it appears to be inactive and no longer valid. 
Please comment and/or reopen if you feel the issue has not been resolved.
