### ISSUE TITLE
How to integrate the CoreUI-Angular with ASP.Net Core 2.0 

### ISSUE THREAD

**Issue by vardhineedik** [coreui/coreui-free-angular-admin-template#35]
Hi 

please help me How to integrate the CoreUI-Angular with ASP.Net Core 2.0 

Thanks,
Krishna

**Comment by xidedix** [comment]
hi @vardhineedik 
there is a tutorial by @mvelosop explaining how to adapt the CoreUI as a base in ASP.NET MVC Core 2 applications https://github.com/mvelosop/AspNetCore2CoreUI

It's not about Angular version of CoreUI specifically, but I suppose it can be useful anyway.

**Comment by hozjanmarko** [comment]
Just copy your angular project to the location of your .net core project. Then edit the .angular-cli.json, and set the out dir property from dist to wwwroot (this will save the bundles to /wwwroot on ng build). Edit your startup.cs, so that your mvc app will serve static files.

**Comment by vardhineedik** [comment]
thank you  @xidedix @hozjanmarko
I am using asp.net core 2.0 angular templet in visualstudio. in that angular app is webpack so unable to integrate the CoreUI can you help me please

**Comment by hozjanmarko** [comment]
By the looks of your screenshot... Start with a blank .net core mvc app, move your controller logic, and then proceed like i described in the previous post. You will be better of in the long run by using angular cli

**Comment by vardhineedik** [comment]
@hozjanmarko 
Thank you, I did same what you say but some issue I am sharing the code with you if you have time please look and solve the problem,
https://github.com/vardhineedik/CoreUiProject
thank you

**Comment by hozjanmarko** [comment]
.angular-cli.json"apps": [

{

"root": "src",

"outDir": "**wwwroot**  "

And in startup.cs, before adding use static files add
app.UseDefaultFiles()
Then run ng build, this will populate the wwwroot folder. Then you can do dotnetrun... Or debug in visual studio

**Comment by vardhineedik** [comment]
I changed above but no luck . can you solve this, please

**Comment by hozjanmarko** [comment]
I will clone it later

**Comment by ColinBlair** [comment]
Microsoft has a new Angular template that uses the Angular CLI. Instructions are at https://github.com/aspnet/JavaScriptServices/issues/1288 until the main documentation gets updated. With the new template, just drop CoreUI into the ClientApp folder.

**Comment by vardhineedik** [comment]
Hi @ColinBlair 
CoreUI not able to add the new template can you guide me any steps for that  

Thanks

**Comment by Cacanny** [comment]
If you're still struggling, I refer to the following: https://www.brandonbarnett.io/blog/2017/06/reference-architecture-angular-4-and-web-api-on-net-core-20-preview-1-with-azure-ad-authentication/

Follow the Web part of this blog, it's very useful and it's serves your purpose. It's not much different what was already said here but maybe it'll give you more information.

**Comment by pratishthap** [comment]
Hi all.I am faving the same issue as Krishna. Please guide us how to integrate core ui angular with asp.net core

**Comment by pratishthap** [comment]
Did anyone get this working. Please help. I cannot make it work

**Comment by guigarma** [comment]
I have not "integrated" this template with .NET Core. But I used another Angular template and it worked for the .NET Core Web App 3.1 template:

- Remove VS default ClientApp contents 
- Paste the template files, they have a similar structure
- Navigate to the ClientApp directory and run from the console `npm install -g @angular/cli@latest`
- Then run `npm install` (this should get all dependencies (node-modules))
- Click Run on VS and after a little while you should be able to see the template as in the demos.
