### ISSUE TITLE
sidebar-compact doesn't work with sidebar-minimized

### ISSUE THREAD

**Issue by taraman** [coreui/coreui-free-angular-admin-template#38]
Dear Team,
Really your theme is awesome, and it help me a lot to understand Angular 2+

I found an issue, when applying "sidebar-compact" on body then try to minimize the sidebar menu by pressing the button at the bottom to minimize it, I got the issue as show in the attached image

thank you for your great theme
![sidebar-compact](https://user-images.githubusercontent.com/914523/33627228-890a789e-da05-11e7-8749-a802d38a4228.png)

**Comment by xidedix** [comment]
Hi @taraman 
Try to remove `sidebar-fixed` class when applying `sidebar-compact` to `<body>` element.
Please let us know if this doesn’t work.

**Comment by taraman** [comment]
still getting the same issue after applying the change u mentioned

by the way, I didn't get your reply on GitHub, I just received this email


thanks,
Taraman
