### ISSUE TITLE
modal popup backdrop issue 

### ISSUE THREAD

**Issue by lakhank295** [coreui/coreui-free-angular-admin-template#39]
hello,
i am facing one issue that is when i login for first time &  generate modal popup dynamically, modal popup executes properly but when i click i on button to close modal popup modal closes but background remains transparent and i cant perform any operation ,means i am facing backdrop issue. when i inspect element & check "<bs-modal-backdrop class="modal-backdrop fade in show"></bs-modal-backdrop>" this remains  as it is. this doesn't remove from DOM on close button. but when i refresh the page all working fine & this line "<bs-modal-backdrop class="modal-backdrop fade in show"></bs-modal-backdrop>" is also remove from DOM.

![errorbackdrop](https://user-images.githubusercontent.com/30143510/33793025-9eb42b04-dcd5-11e7-9cdf-6be037b23e06.png)

following is  the  code & screenshot

 ```
<div bsModal #moduleStatusModal="bs-modal" class="modal fade" [config]="{backdrop: 'static'}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-success" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <i class="fa fa-check-circle-o fa-3x" aria-hidden="true"></i>
                    <h5 class="modal-title">heading goes here</h5>
                    <span> </span>
                </div>
                <div class="modal-body text-center">
                    <div class="finish-info text-center">
                       content goes here
                    </div>
                    <div>
                        content goes here
                    <hr>
                    <button class="btn btn-primary text-center" (click)="moduleComplete()">{{'Stepper.Next' | translate}}</button>
                </div>
            </div>
        </div>
```
ts file code

`
moduleComplete() {
    this.moduleStatusModal.hide();
  }
`

**Comment by adnan-atex** [comment]
Hi - I am having the same issue. According to Modal API, the hide() method does not work through javascript and the modal not close. Please see the code snippet, and advice - if I am doing something wrong here:

**Hide Modal (Code Snippet):**

```
 <ng-template #staticBackdrop>
    <button [cModalToggle]="staticBackdropModal.id" cButton (click)="onFinishAction()">Finish</button>
    <c-modal #staticBackdropModal backdrop="static" id="staticBackdropModal">
      <c-modal-header>
        <h5 cModalTitle>Download Import Template</h5>
        <button [cModalToggle]="staticBackdropModal.id" cButtonClose></button>
      </c-modal-header>
      <c-modal-body>Download the import template. Are you sure?</c-modal-body>
      <c-modal-footer>
        <button (click)="onCloseModalAction()" cButton color="secondary">
          Close
        </button>
        <button cButton color="primary" (click)="onDownloadAction()">Download</button>
      </c-modal-footer>
    </c-modal>
  </ng-template>
```

**Typescript:**

```
const myModal = new coreui.Modal('#staticBackdropModal', {

})
myModal.dispose();
```

**Comment by xidedix** [comment]
@adnan-atex your issue here: https://github.com/coreui/coreui-free-angular-admin-template/issues/245
