### ISSUE TITLE
.breadcrumb-fixed causes breadcrumb to overlap mobile sidebar

### ISSUE THREAD

**Issue by aakashjain** [coreui/coreui-free-angular-admin-template#4]
When using `.sidebar-fixed` and `.breadcrumb-fixed` in mobile layout, opening the sidebar causes the breadcrumb to overlap the sidebar.
IMO the breadcrumb should shift to the right just like the body.

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive. Please comment and/or reopen if you feel the issue has not been resolved.
