### ISSUE TITLE
Dropdown doesn't work

### ISSUE THREAD

**Issue by kmieciu** [coreui/coreui-free-angular-admin-template#40]
I've cloned the latest sources for `Angular4_CLI_Starter` and tried to add `Single button dropdown` example from the documentation to the `dashboard.component.html` . It doesn't work - dropdown button appears but if you click it, nothing happens.

BTW it shows the dropdown if I add `show` class to `dropdownMenuButton` in the Chrome inspect mode.

Please help.

**Comment by vaibhavphutane** [comment]
It means that you did not added or populated the drop down.
HTML
 <div >
         <select ngModel name="agentCode">
          <option value="" selected disabled hidden>Agent Code</option>
            <option *ngFor="let agentcode of agentCodes" [ngValue]="agentcode" >{{agentcode}}</option>
          </select>
  </div>

Populate in .ts
agentCodes=["DHNM001"," DHNM003" ,"DHNM003","DHNM004","DHNM005"];

**Comment by deckerbl** [comment]
I'm having the same problem.  Trying to place a single button drop down in a card header.

**Comment by suleodu** [comment]
same here i am tried to add in a table column
