### ISSUE TITLE
How to use in Angular?

### ISSUE THREAD

**Issue by kotpal** [coreui/coreui-free-angular-admin-template#43]
Looks like the instructions to use CoreUI in an Angular project at http://coreui.io/docs/getting-started/introduction is not complete. 

Specifically how should I import the CoreUI Angular module and use it in my module? Any help will be greatly appreciated

**Comment by kotpal** [comment]
For example, ng-bootstrap provides a simple way to include it via: import {NgbModule} from '@ng-bootstrap/ng-bootstrap'; 

It makes it possible via https://github.com/ng-bootstrap/ng-bootstrap/blob/master/src/index.ts

What is the equivalent way of including CoreUi/Angular module?

**Comment by KK-MarcelJahn** [comment]
Hi @kotpal ,

did you figure out how to integrate it into an already existing app?

Thanks!

**Comment by kotpal** [comment]
I did. I had to essentially make CoreUI the main module and fit my app around it. I have noticed a few issues and I will bring this to your attention soon. I bought the theme, so let me know if there is a different avenue for me to bring these issues to your attention

**Comment by kolkov** [comment]
In its essence, the theme is the folder with the scss and directives. Everything else you can easily integrate into your templates.

**Comment by kotpal** [comment]
It wasn't easy - but yeah we can integrate. It requires some trial and error to get it right (kind of).

**Comment by kolkov** [comment]
Yes, this is not an ordinary php template in joomla.

**Comment by avi613** [comment]
Agree

We need to have an understandable documentation of how to get started with CoreUI and Angular (or any other JS framework).

A nice move would be to produce a step-by-step tutorial as to how to create a Angular + CoreUI white app using angular-cli.
