### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by Deilan** [coreui/coreui-free-angular-admin-template#50]
`npm run test` or `npm run e2e` are both fail.

**Comment by alessandrogurgel** [comment]
Yeah. In appComponent.spec.ts you should import   import { RouterTestingModule } from '@angular/router/testing';

`beforeEach(() => {
    TestBed.configureTestingModule({
      declarations: [
        AppComponent
      ],
      imports: [ RouterTestingModule ]
    });
    TestBed.compileComponents();
  });`

**Comment by alessandrogurgel** [comment]
the other test unit cases related to title can be removed as they do not make sense on the project
