### ISSUE TITLE
How to remove hash from url??

### ISSUE THREAD

**Issue by vinothmoorthkumar** [coreui/coreui-free-angular-admin-template#51]
How to remove hash from url... Because i wants to use facebook auth .. Facebook is not accepting hash url..

**Comment by kolkov** [comment]
https://angular.io/api/common/HashLocationStrategy

**Comment by vinothmoorthkumar** [comment]
Hi @kolkov , thank u for reply....
     I have removed hash.  But now i facing one issue. When i m trying to navigating into children route its working fine bt after refresh the page its not working. because parent param appending in static file path.

for example(before refresh:http://localhost:8000/scripts.bundle.js ,after refresh:http://localhost:8000/components/scripts.bundle.js).

**Comment by kolkov** [comment]
are you sure that you are properly set up `<base href="/">`?

**Comment by kolkov** [comment]
I remove dote before slash in example and and now the example is working!

**Comment by vinothmoorthkumar** [comment]
Thank you @kolkov, Actually <base href="/"> is a problem ...just now i removed dote. now its working properly

**Comment by jogaian282** [comment]
RouterModule.forRoot(yourRoutesHere, { useHash: true })

**Comment by sbasi5576** [comment]
Does it need to be done for each and every individual component?  Or can I enforce it globally?  I have base url set to / and there is useHash:true present in the angular 5 version. Yet, I am seeing # in every url.

**Comment by Ibbus93** [comment]
You have just to remove from app.module.ts the two providers  **LocationStrategy** and **HashLocationStrategy** and it goes good 💯

**Comment by kumarsKavasec** [comment]
remove the **LocationStrategy** and **HashLocationStrategy** in the providers and in the import section from the app.module.ts

**Comment by rajmantechnology** [comment]
Hello,

How can i remove the # from the url in the production mode .

Angular CLI: 1.7.4
Node: 8.11.3
OS: win32 x64
Angular: 5.2.10

app.ts
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core'; 
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { AuthGuard } from './services/auth-gaurd.service';
import { UserService } from './services/user.service';
import { HttpModule } from '@angular/http';
import { FormsModule } from '@angular/forms';
import { RouterModule, Routes } from '@angular/router';
import { SelectDropDownModule } from 'ngx-select-dropdown'
import {GrowlModule} from 'primeng/growl';
import {Message} from 'primeng/api';
import { UserIdleModule } from 'angular-user-idle';
import { MessageService } from 'primeng/components/common/messageservice';
@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        HttpModule,
        SelectDropDownModule,
        BrowserModule,
        AppRoutingModule,
        UserIdleModule.forRoot({idle: 300, timeout: 300, ping: 120})
    ],
    providers: [UserService,AuthGuard,MessageService],
    bootstrap: [AppComponent]
})
export class AppModule { }

app-routingmodule.ts
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

const routes: Routes = [

  {
    path: 'user',
    loadChildren: 'app/user/user.module#UserModule'
  },
  {
    path: '',
    loadChildren: 'app/template/template.module#TemplateModule'
  },
  {
     path: "**",
   redirectTo: "/"
  }


];

@NgModule({
  imports: [RouterModule.forRoot(routes,{useHash:true})],
  exports: [RouterModule]
})
export class AppRoutingModule { }

Plesae help me to solve this isssue.

thank you.

**Comment by indiamerch** [comment]
But , After deploying to server, if i refresh i'll get 404 error. How can i solve it?

**Comment by masonmonu** [comment]
> RouterModule.forRoot(yourRoutesHere, { useHash: false })

**Comment by Roshankrsoni** [comment]
> You have just to remove from app.module.ts the two providers **LocationStrategy** and **HashLocationStrategy** and it goes good

It  worked. Thanks a lot

**Comment by Roshankrsoni** [comment]
<perfect-scrollbar style="height: calc(100% - 33px);">
    <div fxLayout="column" >
        <div *ngIf="!iconOnly" fxLayoutAlign="space-around center" [style.margin]="'10px 0px'" >
          <img width="100" [style.borderRadius]="'50%'" src="./assets/user-image.jpg">
        </div>
        <div *ngIf="iconOnly" style="height: 100px;" fxLayoutAlign="space-around center"  >
            <img width="50" [style.borderRadius]="'50%'" src="./assets/user-image.jpg">
        </div>
        <cdk-sidemenu-item *ngFor="let menu of menus" [menu]="menu" [iconOnly]="iconOnly"> </cdk-sidemenu-item>
    </div>
    
</perfect-scrollbar>

**Comment by Roshankrsoni** [comment]
`
<perfect-scrollbar style="height: calc(100% - 33px);">
    <div fxLayout="column" >
        <div *ngIf="!iconOnly" fxLayoutAlign="space-around center" [style.margin]="'10px 0px'" >
          <img width="100" [style.borderRadius]="'50%'" src="./assets/user-image.jpg">
        </div>
        <div *ngIf="iconOnly" style="height: 100px;" fxLayoutAlign="space-around center"  >
            <img width="50" [style.borderRadius]="'50%'" src="./assets/user-image.jpg">
        </div>
        <cdk-sidemenu-item *ngFor="let menu of menus" [menu]="menu" [iconOnly]="iconOnly"> </cdk-sidemenu-item>
    </div>
    
</perfect-scrollbar>
 `

**Comment by sscots** [comment]
If I download a brand new copy of this repo, then go remove the Provider option from the app.module file (to remove the hash), the inner pages won't load if I go to them and hit refresh (to load them directly). 
For example, if I remove the two providers, then load app, then navigate to "/base/card", then hit the refresh/reload button, it won't display anything.

**Comment by Anderies** [comment]
this article may help you 
https://medium.com/@ndreznotanto/remove-hash-at-url-angular-and-still-be-able-to-refresh-and-not-getting-404-not-found-970312a6e828

**Comment by faiz-webdev** [comment]
> I remove dot before slash in example and and now the example is working!

Thanks @kolkov  working fine.

**Comment by harshaGlovision** [comment]
It's not working in ng build --prod.

**Comment by shsanchit** [comment]
There are lots of ways but here is how it worked for me in Angular 9!
First Create a .htaccess file Paste the following Code And Upload on your prod Server along with your disst prod files.

    RewriteEngine On
    RewriteBase /
    RewriteRule ^index\.html$ - [L]
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule . /index.html [L]
