### ISSUE TITLE
Console Command to create a new view for Core UI Angular

### ISSUE THREAD

**Issue by kurtisane** [coreui/coreui-free-angular-admin-template#56]
Is there a console command that generates a view ? 

It is just annoying to copy a existing view and change all the names and file names to have a new view.

Thanks !

**Comment by xidedix** [comment]
something like `ng generate component [name]` ?

**Comment by kurtisane** [comment]
Yes but ng generate component just generates a component without the module file which is in the example view included.

**Comment by k1ng440** [comment]
```
ng generate module ./views/myview
ng generate component ./views/myview
```
