### ISSUE TITLE
Seems modules are not loading.

### ISSUE THREAD

**Issue by rares-p** [coreui/coreui-free-angular-admin-template#59]
I have a problem,
if I try to do something like {{mycontent | json}} I get an error:

_Template parse errors:
The pipe 'json' could not be found_

If I try to do a reactive form I get:

_Error: Template parse errors:
Can't bind to 'formControl' since it isn't a known property of 'input'._

I do import the modules on the same page:
_import { NgModule, Component, Pipe, OnInit } from "@angular/core";
import { FormGroup, FormControl, FormsModule } from "@angular/forms";
import { BrowserModule } from "@angular/platform-browser";_

_@NgModule({
  imports: [CommonModule, FormsModule, BrowserModule]
})_

Seems to me the modules loading does not work, or I don't understand how.
If I get an angular seed project it works out of the box.

Thanks in advance,
Rares

**Comment by Darkhate3d** [comment]
Ive got same error

**Comment by rares-p** [comment]
I 'fixed it' by making a new project:
`ng new my-proj --style=scss`
and then I imported all the stuff from the CoreUI project. It works now.

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive or answered above. Please comment and/or reopen if you feel the issue has not been resolved.
