### ISSUE TITLE
How to navigate to child route on edit

### ISSUE THREAD

**Issue by xts-velkumars** [coreui/coreui-free-angular-admin-template#64]
Good day, 

I have a route for user similar to dashboard, where i have a table to display list of users in my system. Its working as excepted. when i click edit i would like to navigate to a new route, i'm facing issue here. I couldn't navigate to new route, below is my route configuration. It would be really appreciated if some one help me to resolve this  

**Excepted result**
http://localhost:4200/user - Grid page
http://localhost:4200/user/1 - Edit page

**Breadcrumbs** 
Home / User
Home / User / User Details

**_nav.ts**
```
export const navigation = [
  {
    name: 'Dashboard',
    url: '/dashboard',
    icon: 'icon-speedometer',
    badge: {
      variant: 'info'
    }
  },
  {
    name: 'User',
    url: '/user',
    icon: 'icon-speedometer',
    badge: {
      variant: 'info'
    }
  }
];

```
**app.routing.ts**
```
export const routes: Routes = [
  {
    path: '',
    redirectTo: 'dashboard',
    pathMatch: 'full',
  },
  {
    path: '',
    component: FullLayoutComponent,
    data: {
      title: 'Home'
    },
    children: [
      {
        path: 'dashboard',
        loadChildren: './views/dashboard/dashboard.module#DashboardModule'
      },
      {
        path: 'user',
        loadChildren: './views/user/user.module#UserModule',
      } 
    ]
  },
  {
    path: 'login',
    component: SimpleLayoutComponent,
    data: {
      title: ''
    },
    children: [
      {
        path: '',
        loadChildren: './views/login/login.module#LoginModule',
      }
    ]
  }
];
```

**user-routing.module.ts**

```
const routes: Routes = [
  {
    path: '',
    component: UserComponent,
    data: {
      title: 'User'
    },
    children: [
      {
        path: 'user/:id',
        component: UserDetailsComponent,
        data: {
          title: 'User Details'
        }
      }
    ]
  }
];
```

**Comment by nileshpadwal** [comment]
So did you get any solution to your problem?
I am also in the similar situation. I do not have :id in my path yet. Only parent (user) component and child (details) component. 

If I use `<div class="btn routerLink="details"> Details </div>` from parent component template, only breadcrumb is updated to `Home / User / Details` and url in the browser is updated to `/user/details`. Parent component stays on screen and child component is not rendered. Also I did a console.log in constructor and init of child component but neither is called in this case.

If I move the child (details) component from children list to main list of (user) component in user-routing.module.ts, the child component is rendered but I loose on hierarchy. Only `Home/Details` is displayed in breadcrumb and also url shows only '/details'. I want to retain the hierarchy.

**Comment by btmfinancials** [comment]
I am getting the similar problem. anyone having the solution then please reply?
i want url like www.abc.com\blog\product1, www.abc.com\blog\product2 etc where product1 and product2 will be generated dynamically. but i am unable to set it. in app.routing.ts i placed it as below:
{
    path: 'blogs',
    component: BlogComponent,
    data: {
      title: 'Blog'
    },    
    children:[
      {
        path: "product/:name",
        component: ProductComponent,
        data: {
          title: "prod  Page"
        }
      }
    ]
  }

**Comment by xidedix** [comment]
@btmfinancials 

Please describe where is the problem actually?
see: 
- https://angular.io/guide/router#link-parameters-array
- https://angular.io/api/router/RouterLink#setting-and-handling-query-params-and-fragments

If you need to pass `queryParams` to sidebar-nav navItems (_nav.ts), use `linkProps: INavLinkProps`, sth like:
```js
  {
    name: 'Product 1',
    url: 'product',
    linkProps: { queryParams: { product: 1 } },
  },
```

see: https://coreui.io/angular/docs/components/sidebar#inavdata
