### ISSUE TITLE
Angular Directives

### ISSUE THREAD

**Issue by Prinos** [coreui/coreui-free-angular-admin-template#68]
I want to add Angular Directives such as *ngFor, *ngIf. but I have error
`Can't bind to 'ngIf' since it isn't a known property of 'div'. ("
        <div class="card-body">
            <div [ERROR ->]*ngIf="boo">Boo</div>
        </div>`

Please help me to fix it.

**Comment by Boboss74** [comment]
first result:
http://lmgtfy.com/?q=Can%27t+bind+to+%27ngIf%27+since+it+isn%27t+a+known+property+of+%27div%27

**Comment by hamduc7** [comment]
I have this same issue
