### ISSUE TITLE
How can I add core ui angular admin template to an existing project?

### ISSUE THREAD

**Issue by seatechdev** [coreui/coreui-free-angular-admin-template#70]
Can someone please guide me?  I have an existing Angular 5 project with authentication in place.  I would like to add this project as part of it.  I would like to use the CSS of this project in my existing project as well.

**Comment by danlupascu** [comment]
+1

**Comment by jmdmao** [comment]
+1

**Comment by mokipedia** [comment]
This template is a litte more than just it's scss/css parts.
You can migrate your current project to this as a starter. this should not be too hard, but will require a litte bit of work on your end. This should be easier, as you are already familiar with your projects structure and hopefully know what parts you need.
As I hope both projects are based on Angular-CLI the main setup should look very similar.

the basic steps could look something like this:
- create a new project folder and clone this project
- copy your components to the app folder (or the corresponding subfolders you had them in) of this project
- add npm dependencies to package.json according to your project
- add custom scss of your other project to the file in this project readied for you (there is one for custom css). if you have scss in components, simply copy them with your component, no other steps needed.
- add routes of your components to the routing files where you need them. keep in mind that you have to add them to the layout you prefer (simple, full). This is the part where the sidebar etc will be injected if you need that.
- extend the module imports, exports, provider etc for your components to be registered/loaded (just as you did with your other project)
- you may need to change your html templates to get the design you want and make it bootstrap 4 compliant.

the other way around might be more complicated, depending on the size of your current project. It would still be more or less the same steps. you will still need to copy files and components, add dependencies that are not there, extend the module and change the routes to be parented by eigher layout. you could forego the layout and implement the components directly, but I find that to be bad habit and fairly ugly. modularize your code where possible and usefull.
