### ISSUE TITLE
Role Based Navigation

### ISSUE THREAD

**Issue by prakash403** [coreui/coreui-free-angular-admin-template#75]
Is Role based navigation support this template , Admin and user.  Please advice

**Comment by jameelmohd000** [comment]
Based on role how I should filter the nav sidebar

**Comment by hvsharma63** [comment]
I've created different array of objects for different roles in **_nav.ts** file. You can create object's list like that and map/filter out different objects based on roles in layout component ts file.

**_nav.ts**
`export const adminNavItems = [
  {
    ....
  }
];`

**layout.component.ts** 's constructor()
`const currentUser = this.authService.currentUserValue;
    switch (currentUser.role) {
      case "superadmin":
        ....
        break;
      default:
        break;
    }
`

**layout.component.html**
    `<app-sidebar-nav [navItems]="navItems" [perfectScrollbar] [disabled]="appSidebar.minimized"></app-sidebar-nav>`


> Based on role how I should filter the nav sidebar
