### ISSUE TITLE
With large number of menu items, app-sidebar - appsidebarminimizer button is hidden when app-sidebar is minimized

### ISSUE THREAD

**Issue by david-palladino** [coreui/coreui-free-angular-admin-template#86]
I'm using @coreui/coreui 2.0.1 and @coreui/angular 2.0.0-rc.0.  The appsidebarminimizer button is hidden in the app-sidebar when there are a large number of menu items in the _nav.ts - navItems array.  This prevents the app-sidebar from being maximized after it has been minimized.  The only way to maximize the app-sidebar in this state is to refresh the browser.

I've traced the problem.  When maximized the app-sidebar-nav has class="sidebar-nav ps ps-active-y".  This allows for the appsidebarminimizer button to display.  But when the app-sidebar is minimized then app-sidebar-nav has class="sidebar-nav" without the "ps ps-active-y" part.  If "ps ps-active-y" is always included then this should fix the issue.  

Thanks for any fixes you can provide us.  CoreUI is fantastic, I love it.  Thanks!

**Comment by mrholek** [comment]
When reporting a bug, include:

- Operating system and version (Windows, Mac OS X, Android, iOS, Win10 Mobile)
- Browser and version (Chrome, Firefox, Safari, IE, MS Edge, Opera 15+, Android Browser)
- Reduced test cases and potential fixes using [CodePen](https://codepen.io/) or [JS Bin](https://jsbin.com/)
