### ISSUE TITLE
making the sidebar minimized by default

### ISSUE THREAD

**Issue by naz2112** [coreui/coreui-free-angular-admin-template#87]

**Comment by sudha1981** [comment]
any one know how to hide the making the sidebar minimized by default

**Comment by viveksh09876** [comment]
You can add this class on body tag: "sidebar-minimized" to make sidebar minimized by default.

**Comment by xidedix** [comment]
if you are going to use `sidebar-minimized` class on `body` of `index.html` you may want to add class `brand-minimized` also

```html
<body class="app sidebar-minimized brand-minimized">
  <!-- App Loading... -->
</body>
```

**Comment by rashnk** [comment]
```

left sidebar <app-sidebar   [display]="false">
right sidebar <app-aside   [display]="false">


```

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive or answered above. Please comment and/or reopen if you feel the issue has not been resolved.

**Comment by stephenmutua254** [comment]
@xidedix I tried your trick but no luck.

**Comment by scottyh527** [comment]
Any way of having the sidebar minimizer show  even on smaller screens?

**Comment by xidedix** [comment]
Hi @scottyh527 

To shift mobile breakpoint of your template one step down:
1. in `src/scss/_variables.scss`
```scss
// Variable overrides
$breakpoint-mobile-up: md;
$breakpoint-mobile-down: sm;
```
2. in `src/app/containers/default-layout/default-layout.component.html`
set toggler and sidebar breakpoints to `md`
```html
<app-header
  ...
  [sidebarToggler]="'md'"
  [asideMenuToggler]="'md'">
...
```
```html
  <app-sidebar [fixed]="true" [display]="'md'">

```

**Comment by scottyh527** [comment]
@xidedix thanks that helped, though for AppSidebarMinimizer i tried setting display to 'sm' but below 768 px it disappears. This is the chevron icon that shrinks the app side bar.

**Comment by scottyh527** [comment]
@xidedix I looked at the node_module file for the sidebarminimizer in the react coreui, the only proptypes for it seems to be children, classname, tag, and type. Is there no way to make the chevron thing that minimizes the side nav bar responsive?
