### ISSUE TITLE
"sidebar-lg-show sidebar-fixed" classes not removed from body tag when returned to login page from dashboard

### ISSUE THREAD

**Issue by viveksh09876** [coreui/coreui-free-angular-admin-template#93]
"sidebar-lg-show sidebar-fixed" classes does not get removed from body tag when returned to login page from dashboard page. This makes the login page misaligned from center.
![err2](https://user-images.githubusercontent.com/8949503/41763235-5151da52-761b-11e8-9f8a-fb146f13ba87.PNG)

**Comment by xidedix** [comment]
hi @viveksh09876 
please update `@coreui/angular` to `^2.2.1`
