### ISSUE TITLE
How to add sidebar footer

### ISSUE THREAD

**Issue by elieobeid7** [coreui/coreui-free-angular-admin-template#98]
In the compiled files of the sidebar, i see a file called sidebar footer, but I don't see an example of adding a footer to the sidebar. It would be nice to add the logout button in the sidebar footer. How to do so?

**Comment by xidedix** [comment]
Hi @elieobeid7 
Modify `default-layout.component.html` adding `app-sidebar-footer` inside `app-sidebar` like this:  
````html
...  
<app-sidebar ...>
  ...
  <app-sidebar-footer>Footer</app-sidebar-footer>
  <app-sidebar-minimizer></app-sidebar-minimizer>
</app-sidebar>
...
````

**Comment by elieobeid7** [comment]
@xidedix  worked perfectly but it's not well aligned with the rest of sidebar items

![capture](https://user-images.githubusercontent.com/660142/43909067-2900e392-9c02-11e8-939d-201332c59a4e.PNG)

My code

```
    <app-sidebar-footer>
      <li class="nav-item" ng-reflect-ng-class="nav-item" style="list-style: none;">
        <a routerlinkactive="active" class="nav-link" ng-reflect-ng-class="nav-link" ng-reflect-router-link="/logout" ng-reflect-router-link-active="active"
          href="logout">
          <i class="nav-icon icon-logout"></i> Logout
        </a>
      </li>
    </app-sidebar-footer>
    <app-sidebar-minimizer></app-sidebar-minimizer>
```

This is the same code that is used by the sidebar, I copied it, changed the word and logout icon. Do you know why items in footer aren't well aligned?

**Comment by elieobeid7** [comment]
`.sidebar .sidebar-footer` has unnecessary padding that I wish it was removed, it was causing the problem, thanks again for your help
